// Copyright 2024 Golden M, Inc. All rights reserved.
// Use of this source code is governed by an MIT-style license that can be
// found in the LICENSE file.
// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#undef _HAS_EXCEPTIONS

#include "messages.g.h"

#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace layrz_wifi {
using flutter::BasicMessageChannel;
using flutter::CustomEncodableValue;
using flutter::EncodableList;
using flutter::EncodableMap;
using flutter::EncodableValue;

FlutterError CreateConnectionError(const std::string channel_name) {
  return FlutterError(
      "channel-error",
      "Unable to establish connection on channel: '" + channel_name + "'.",
      EncodableValue(""));
}

// WifiNetwork

WifiNetwork::WifiNetwork(
  const std::string& ssid,
  const WifiSecurity& security,
  bool is_hidden)
 : ssid_(ssid),
    security_(security),
    is_hidden_(is_hidden) {}

WifiNetwork::WifiNetwork(
  const std::string& ssid,
  const std::string* bssid,
  const int64_t* signal_dbm,
  const int64_t* frequency_mhz,
  const WifiSecurity& security,
  bool is_hidden)
 : ssid_(ssid),
    bssid_(bssid ? std::optional<std::string>(*bssid) : std::nullopt),
    signal_dbm_(signal_dbm ? std::optional<int64_t>(*signal_dbm) : std::nullopt),
    frequency_mhz_(frequency_mhz ? std::optional<int64_t>(*frequency_mhz) : std::nullopt),
    security_(security),
    is_hidden_(is_hidden) {}

const std::string& WifiNetwork::ssid() const {
  return ssid_;
}

void WifiNetwork::set_ssid(std::string_view value_arg) {
  ssid_ = value_arg;
}


const std::string* WifiNetwork::bssid() const {
  return bssid_ ? &(*bssid_) : nullptr;
}

void WifiNetwork::set_bssid(const std::string_view* value_arg) {
  bssid_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void WifiNetwork::set_bssid(std::string_view value_arg) {
  bssid_ = value_arg;
}


const int64_t* WifiNetwork::signal_dbm() const {
  return signal_dbm_ ? &(*signal_dbm_) : nullptr;
}

void WifiNetwork::set_signal_dbm(const int64_t* value_arg) {
  signal_dbm_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void WifiNetwork::set_signal_dbm(int64_t value_arg) {
  signal_dbm_ = value_arg;
}


const int64_t* WifiNetwork::frequency_mhz() const {
  return frequency_mhz_ ? &(*frequency_mhz_) : nullptr;
}

void WifiNetwork::set_frequency_mhz(const int64_t* value_arg) {
  frequency_mhz_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void WifiNetwork::set_frequency_mhz(int64_t value_arg) {
  frequency_mhz_ = value_arg;
}


const WifiSecurity& WifiNetwork::security() const {
  return security_;
}

void WifiNetwork::set_security(const WifiSecurity& value_arg) {
  security_ = value_arg;
}


bool WifiNetwork::is_hidden() const {
  return is_hidden_;
}

void WifiNetwork::set_is_hidden(bool value_arg) {
  is_hidden_ = value_arg;
}


EncodableList WifiNetwork::ToEncodableList() const {
  EncodableList list;
  list.reserve(6);
  list.push_back(EncodableValue(ssid_));
  list.push_back(bssid_ ? EncodableValue(*bssid_) : EncodableValue());
  list.push_back(signal_dbm_ ? EncodableValue(*signal_dbm_) : EncodableValue());
  list.push_back(frequency_mhz_ ? EncodableValue(*frequency_mhz_) : EncodableValue());
  list.push_back(CustomEncodableValue(security_));
  list.push_back(EncodableValue(is_hidden_));
  return list;
}

WifiNetwork WifiNetwork::FromEncodableList(const EncodableList& list) {
  WifiNetwork decoded(
    std::get<std::string>(list[0]),
    std::any_cast<const WifiSecurity&>(std::get<CustomEncodableValue>(list[4])),
    std::get<bool>(list[5]));
  auto& encodable_bssid = list[1];
  if (!encodable_bssid.IsNull()) {
    decoded.set_bssid(std::get<std::string>(encodable_bssid));
  }
  auto& encodable_signal_dbm = list[2];
  if (!encodable_signal_dbm.IsNull()) {
    decoded.set_signal_dbm(std::get<int64_t>(encodable_signal_dbm));
  }
  auto& encodable_frequency_mhz = list[3];
  if (!encodable_frequency_mhz.IsNull()) {
    decoded.set_frequency_mhz(std::get<int64_t>(encodable_frequency_mhz));
  }
  return decoded;
}


PigeonInternalCodecSerializer::PigeonInternalCodecSerializer() {}

EncodableValue PigeonInternalCodecSerializer::ReadValueOfType(
  uint8_t type,
  flutter::ByteStreamReader* stream) const {
  switch (type) {
    case 129: {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<WifiSecurity>(enum_arg_value));
      }
    case 130: {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<WifiPermissionStatus>(enum_arg_value));
      }
    case 131: {
        return CustomEncodableValue(WifiNetwork::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    default:
      return flutter::StandardCodecSerializer::ReadValueOfType(type, stream);
    }
}

void PigeonInternalCodecSerializer::WriteValue(
  const EncodableValue& value,
  flutter::ByteStreamWriter* stream) const {
  if (const CustomEncodableValue* custom_value = std::get_if<CustomEncodableValue>(&value)) {
    if (custom_value->type() == typeid(WifiSecurity)) {
      stream->WriteByte(129);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<WifiSecurity>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(WifiPermissionStatus)) {
      stream->WriteByte(130);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<WifiPermissionStatus>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(WifiNetwork)) {
      stream->WriteByte(131);
      WriteValue(EncodableValue(std::any_cast<WifiNetwork>(*custom_value).ToEncodableList()), stream);
      return;
    }
  }
  flutter::StandardCodecSerializer::WriteValue(value, stream);
}

/// The codec used by LayrzWifiApi.
const flutter::StandardMessageCodec& LayrzWifiApi::GetCodec() {
  return flutter::StandardMessageCodec::GetInstance(&PigeonInternalCodecSerializer::GetInstance());
}

// Sets up an instance of `LayrzWifiApi` to handle messages through the `binary_messenger`.
void LayrzWifiApi::SetUp(
  flutter::BinaryMessenger* binary_messenger,
  LayrzWifiApi* api) {
  LayrzWifiApi::SetUp(binary_messenger, api, "");
}

void LayrzWifiApi::SetUp(
  flutter::BinaryMessenger* binary_messenger,
  LayrzWifiApi* api,
  const std::string& message_channel_suffix) {
  const std::string prepended_suffix = message_channel_suffix.length() > 0 ? std::string(".") + message_channel_suffix : "";
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.layrz_wifi.LayrzWifiApi.hasDiscovery" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          ErrorOr<bool> output = api->HasDiscovery();
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.layrz_wifi.LayrzWifiApi.hasCurrentSsid" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          ErrorOr<bool> output = api->HasCurrentSsid();
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.layrz_wifi.LayrzWifiApi.currentSsid" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          ErrorOr<std::optional<std::string>> output = api->CurrentSsid();
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          auto output_optional = std::move(output).TakeValue();
          if (output_optional) {
            wrapped.push_back(EncodableValue(std::move(output_optional).value()));
          } else {
            wrapped.push_back(EncodableValue());
          }
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.layrz_wifi.LayrzWifiApi.scan" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          ErrorOr<EncodableList> output = api->Scan();
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.layrz_wifi.LayrzWifiApi.ensurePermissions" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          ErrorOr<WifiPermissionStatus> output = api->EnsurePermissions();
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
}

EncodableValue LayrzWifiApi::WrapError(std::string_view error_message) {
  return EncodableValue(EncodableList{
    EncodableValue(std::string(error_message)),
    EncodableValue("Error"),
    EncodableValue()
  });
}

EncodableValue LayrzWifiApi::WrapError(const FlutterError& error) {
  return EncodableValue(EncodableList{
    EncodableValue(error.code()),
    EncodableValue(error.message()),
    error.details()
  });
}

}  // namespace layrz_wifi
