// Copyright 2024 Golden M, Inc. All rights reserved.
// Use of this source code is governed by an MIT-style license that can be
// found in the LICENSE file.
// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_MESSAGES_G_H_
#define PIGEON_MESSAGES_G_H_
#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace layrz_wifi {


// Generated class from Pigeon.

class FlutterError {
 public:
  explicit FlutterError(const std::string& code)
    : code_(code) {}
  explicit FlutterError(const std::string& code, const std::string& message)
    : code_(code), message_(message) {}
  explicit FlutterError(const std::string& code, const std::string& message, const flutter::EncodableValue& details)
    : code_(code), message_(message), details_(details) {}

  const std::string& code() const { return code_; }
  const std::string& message() const { return message_; }
  const flutter::EncodableValue& details() const { return details_; }

 private:
  std::string code_;
  std::string message_;
  flutter::EncodableValue details_;
};

template<class T> class ErrorOr {
 public:
  ErrorOr(const T& rhs) : v_(rhs) {}
  ErrorOr(const T&& rhs) : v_(std::move(rhs)) {}
  ErrorOr(const FlutterError& rhs) : v_(rhs) {}
  ErrorOr(const FlutterError&& rhs) : v_(std::move(rhs)) {}

  bool has_error() const { return std::holds_alternative<FlutterError>(v_); }
  const T& value() const { return std::get<T>(v_); };
  const FlutterError& error() const { return std::get<FlutterError>(v_); };

 private:
  friend class LayrzWifiApi;
  ErrorOr() = default;
  T TakeValue() && { return std::get<T>(std::move(v_)); }

  std::variant<T, FlutterError> v_;
};


enum class WifiSecurity {
  kOpen = 0,
  kWep = 1,
  kWpa = 2,
  kWpa2 = 3,
  kWpa3 = 4,
  kUnknown = 5
};

enum class WifiPermissionStatus {
  kGranted = 0,
  kDenied = 1,
  kPermanentlyDenied = 2,
  kRestricted = 3,
  kNotRequired = 4
};


// Generated class from Pigeon that represents data sent in messages.
class WifiNetwork {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit WifiNetwork(
    const std::string& ssid,
    const WifiSecurity& security,
    bool is_hidden);

  // Constructs an object setting all fields.
  explicit WifiNetwork(
    const std::string& ssid,
    const std::string* bssid,
    const int64_t* signal_dbm,
    const int64_t* frequency_mhz,
    const WifiSecurity& security,
    bool is_hidden);

  const std::string& ssid() const;
  void set_ssid(std::string_view value_arg);

  const std::string* bssid() const;
  void set_bssid(const std::string_view* value_arg);
  void set_bssid(std::string_view value_arg);

  const int64_t* signal_dbm() const;
  void set_signal_dbm(const int64_t* value_arg);
  void set_signal_dbm(int64_t value_arg);

  const int64_t* frequency_mhz() const;
  void set_frequency_mhz(const int64_t* value_arg);
  void set_frequency_mhz(int64_t value_arg);

  const WifiSecurity& security() const;
  void set_security(const WifiSecurity& value_arg);

  bool is_hidden() const;
  void set_is_hidden(bool value_arg);


 private:
  static WifiNetwork FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class LayrzWifiApi;
  friend class PigeonInternalCodecSerializer;
  std::string ssid_;
  std::optional<std::string> bssid_;
  std::optional<int64_t> signal_dbm_;
  std::optional<int64_t> frequency_mhz_;
  WifiSecurity security_;
  bool is_hidden_;

};


class PigeonInternalCodecSerializer : public flutter::StandardCodecSerializer {
 public:
  PigeonInternalCodecSerializer();
  inline static PigeonInternalCodecSerializer& GetInstance() {
    static PigeonInternalCodecSerializer sInstance;
    return sInstance;
  }

  void WriteValue(
    const flutter::EncodableValue& value,
    flutter::ByteStreamWriter* stream) const override;

 protected:
  flutter::EncodableValue ReadValueOfType(
    uint8_t type,
    flutter::ByteStreamReader* stream) const override;

};

// Generated interface from Pigeon that represents a handler of messages from Flutter.
class LayrzWifiApi {
 public:
  LayrzWifiApi(const LayrzWifiApi&) = delete;
  LayrzWifiApi& operator=(const LayrzWifiApi&) = delete;
  virtual ~LayrzWifiApi() {}
  virtual ErrorOr<bool> HasDiscovery() = 0;
  virtual ErrorOr<bool> HasCurrentSsid() = 0;
  virtual ErrorOr<std::optional<std::string>> CurrentSsid() = 0;
  virtual ErrorOr<flutter::EncodableList> Scan() = 0;
  virtual ErrorOr<WifiPermissionStatus> EnsurePermissions() = 0;

  // The codec used by LayrzWifiApi.
  static const flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `LayrzWifiApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    LayrzWifiApi* api);
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    LayrzWifiApi* api,
    const std::string& message_channel_suffix);
  static flutter::EncodableValue WrapError(std::string_view error_message);
  static flutter::EncodableValue WrapError(const FlutterError& error);

 protected:
  LayrzWifiApi() = default;

};
}  // namespace layrz_wifi
#endif  // PIGEON_MESSAGES_G_H_
