// Copyright 2026 Golden M, Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the “Software”), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_MESSAGES_G_H_
#define PIGEON_MESSAGES_G_H_

#include <flutter_linux/flutter_linux.h>

G_BEGIN_DECLS

/**
 * LayrzWifiWifiSecurity:
 * LAYRZ_WIFI_WIFI_SECURITY_OPEN:
 * LAYRZ_WIFI_WIFI_SECURITY_WEP:
 * LAYRZ_WIFI_WIFI_SECURITY_WPA:
 * LAYRZ_WIFI_WIFI_SECURITY_WPA2:
 * LAYRZ_WIFI_WIFI_SECURITY_WPA3:
 * LAYRZ_WIFI_WIFI_SECURITY_UNKNOWN:
 *
 */
typedef enum {
  LAYRZ_WIFI_WIFI_SECURITY_OPEN = 0,
  LAYRZ_WIFI_WIFI_SECURITY_WEP = 1,
  LAYRZ_WIFI_WIFI_SECURITY_WPA = 2,
  LAYRZ_WIFI_WIFI_SECURITY_WPA2 = 3,
  LAYRZ_WIFI_WIFI_SECURITY_WPA3 = 4,
  LAYRZ_WIFI_WIFI_SECURITY_UNKNOWN = 5
} LayrzWifiWifiSecurity;

/**
 * LayrzWifiWifiPermissionStatus:
 * LAYRZ_WIFI_WIFI_PERMISSION_STATUS_GRANTED:
 * LAYRZ_WIFI_WIFI_PERMISSION_STATUS_DENIED:
 * LAYRZ_WIFI_WIFI_PERMISSION_STATUS_PERMANENTLY_DENIED:
 * LAYRZ_WIFI_WIFI_PERMISSION_STATUS_RESTRICTED:
 * LAYRZ_WIFI_WIFI_PERMISSION_STATUS_NOT_REQUIRED:
 *
 */
typedef enum {
  LAYRZ_WIFI_WIFI_PERMISSION_STATUS_GRANTED = 0,
  LAYRZ_WIFI_WIFI_PERMISSION_STATUS_DENIED = 1,
  LAYRZ_WIFI_WIFI_PERMISSION_STATUS_PERMANENTLY_DENIED = 2,
  LAYRZ_WIFI_WIFI_PERMISSION_STATUS_RESTRICTED = 3,
  LAYRZ_WIFI_WIFI_PERMISSION_STATUS_NOT_REQUIRED = 4
} LayrzWifiWifiPermissionStatus;

/**
 * LayrzWifiWifiNetwork:
 *
 */

G_DECLARE_FINAL_TYPE(LayrzWifiWifiNetwork, layrz_wifi_wifi_network, LAYRZ_WIFI, WIFI_NETWORK, GObject)

/**
 * layrz_wifi_wifi_network_new:
 * ssid: field in this object.
 * bssid: field in this object.
 * signal_dbm: field in this object.
 * frequency_mhz: field in this object.
 * security: field in this object.
 * is_hidden: field in this object.
 *
 * Creates a new #WifiNetwork object.
 *
 * Returns: a new #LayrzWifiWifiNetwork
 */
LayrzWifiWifiNetwork* layrz_wifi_wifi_network_new(const gchar* ssid, const gchar* bssid, int64_t* signal_dbm, int64_t* frequency_mhz, LayrzWifiWifiSecurity security, gboolean is_hidden);

/**
 * layrz_wifi_wifi_network_get_ssid
 * @object: a #LayrzWifiWifiNetwork.
 *
 * Gets the value of the ssid field of @object.
 *
 * Returns: the field value.
 */
const gchar* layrz_wifi_wifi_network_get_ssid(LayrzWifiWifiNetwork* object);

/**
 * layrz_wifi_wifi_network_get_bssid
 * @object: a #LayrzWifiWifiNetwork.
 *
 * Gets the value of the bssid field of @object.
 *
 * Returns: the field value.
 */
const gchar* layrz_wifi_wifi_network_get_bssid(LayrzWifiWifiNetwork* object);

/**
 * layrz_wifi_wifi_network_get_signal_dbm
 * @object: a #LayrzWifiWifiNetwork.
 *
 * Gets the value of the signalDbm field of @object.
 *
 * Returns: the field value.
 */
int64_t* layrz_wifi_wifi_network_get_signal_dbm(LayrzWifiWifiNetwork* object);

/**
 * layrz_wifi_wifi_network_get_frequency_mhz
 * @object: a #LayrzWifiWifiNetwork.
 *
 * Gets the value of the frequencyMhz field of @object.
 *
 * Returns: the field value.
 */
int64_t* layrz_wifi_wifi_network_get_frequency_mhz(LayrzWifiWifiNetwork* object);

/**
 * layrz_wifi_wifi_network_get_security
 * @object: a #LayrzWifiWifiNetwork.
 *
 * Gets the value of the security field of @object.
 *
 * Returns: the field value.
 */
LayrzWifiWifiSecurity layrz_wifi_wifi_network_get_security(LayrzWifiWifiNetwork* object);

/**
 * layrz_wifi_wifi_network_get_is_hidden
 * @object: a #LayrzWifiWifiNetwork.
 *
 * Gets the value of the isHidden field of @object.
 *
 * Returns: the field value.
 */
gboolean layrz_wifi_wifi_network_get_is_hidden(LayrzWifiWifiNetwork* object);

G_DECLARE_FINAL_TYPE(LayrzWifiMessageCodec, layrz_wifi_message_codec, LAYRZ_WIFI, MESSAGE_CODEC, FlStandardMessageCodec)

G_DECLARE_FINAL_TYPE(LayrzWifiLayrzWifiApi, layrz_wifi_layrz_wifi_api, LAYRZ_WIFI, LAYRZ_WIFI_API, GObject)

G_DECLARE_FINAL_TYPE(LayrzWifiLayrzWifiApiHasDiscoveryResponse, layrz_wifi_layrz_wifi_api_has_discovery_response, LAYRZ_WIFI, LAYRZ_WIFI_API_HAS_DISCOVERY_RESPONSE, GObject)

/**
 * layrz_wifi_layrz_wifi_api_has_discovery_response_new:
 *
 * Creates a new response to LayrzWifiApi.hasDiscovery.
 *
 * Returns: a new #LayrzWifiLayrzWifiApiHasDiscoveryResponse
 */
LayrzWifiLayrzWifiApiHasDiscoveryResponse* layrz_wifi_layrz_wifi_api_has_discovery_response_new(gboolean return_value);

/**
 * layrz_wifi_layrz_wifi_api_has_discovery_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to LayrzWifiApi.hasDiscovery.
 *
 * Returns: a new #LayrzWifiLayrzWifiApiHasDiscoveryResponse
 */
LayrzWifiLayrzWifiApiHasDiscoveryResponse* layrz_wifi_layrz_wifi_api_has_discovery_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(LayrzWifiLayrzWifiApiHasCurrentSsidResponse, layrz_wifi_layrz_wifi_api_has_current_ssid_response, LAYRZ_WIFI, LAYRZ_WIFI_API_HAS_CURRENT_SSID_RESPONSE, GObject)

/**
 * layrz_wifi_layrz_wifi_api_has_current_ssid_response_new:
 *
 * Creates a new response to LayrzWifiApi.hasCurrentSsid.
 *
 * Returns: a new #LayrzWifiLayrzWifiApiHasCurrentSsidResponse
 */
LayrzWifiLayrzWifiApiHasCurrentSsidResponse* layrz_wifi_layrz_wifi_api_has_current_ssid_response_new(gboolean return_value);

/**
 * layrz_wifi_layrz_wifi_api_has_current_ssid_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to LayrzWifiApi.hasCurrentSsid.
 *
 * Returns: a new #LayrzWifiLayrzWifiApiHasCurrentSsidResponse
 */
LayrzWifiLayrzWifiApiHasCurrentSsidResponse* layrz_wifi_layrz_wifi_api_has_current_ssid_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(LayrzWifiLayrzWifiApiCurrentSsidResponse, layrz_wifi_layrz_wifi_api_current_ssid_response, LAYRZ_WIFI, LAYRZ_WIFI_API_CURRENT_SSID_RESPONSE, GObject)

/**
 * layrz_wifi_layrz_wifi_api_current_ssid_response_new:
 *
 * Creates a new response to LayrzWifiApi.currentSsid.
 *
 * Returns: a new #LayrzWifiLayrzWifiApiCurrentSsidResponse
 */
LayrzWifiLayrzWifiApiCurrentSsidResponse* layrz_wifi_layrz_wifi_api_current_ssid_response_new(const gchar* return_value);

/**
 * layrz_wifi_layrz_wifi_api_current_ssid_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to LayrzWifiApi.currentSsid.
 *
 * Returns: a new #LayrzWifiLayrzWifiApiCurrentSsidResponse
 */
LayrzWifiLayrzWifiApiCurrentSsidResponse* layrz_wifi_layrz_wifi_api_current_ssid_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(LayrzWifiLayrzWifiApiStartScanResponse, layrz_wifi_layrz_wifi_api_start_scan_response, LAYRZ_WIFI, LAYRZ_WIFI_API_START_SCAN_RESPONSE, GObject)

/**
 * layrz_wifi_layrz_wifi_api_start_scan_response_new:
 *
 * Creates a new response to LayrzWifiApi.startScan.
 *
 * Returns: a new #LayrzWifiLayrzWifiApiStartScanResponse
 */
LayrzWifiLayrzWifiApiStartScanResponse* layrz_wifi_layrz_wifi_api_start_scan_response_new();

/**
 * layrz_wifi_layrz_wifi_api_start_scan_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to LayrzWifiApi.startScan.
 *
 * Returns: a new #LayrzWifiLayrzWifiApiStartScanResponse
 */
LayrzWifiLayrzWifiApiStartScanResponse* layrz_wifi_layrz_wifi_api_start_scan_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(LayrzWifiLayrzWifiApiStopScanResponse, layrz_wifi_layrz_wifi_api_stop_scan_response, LAYRZ_WIFI, LAYRZ_WIFI_API_STOP_SCAN_RESPONSE, GObject)

/**
 * layrz_wifi_layrz_wifi_api_stop_scan_response_new:
 *
 * Creates a new response to LayrzWifiApi.stopScan.
 *
 * Returns: a new #LayrzWifiLayrzWifiApiStopScanResponse
 */
LayrzWifiLayrzWifiApiStopScanResponse* layrz_wifi_layrz_wifi_api_stop_scan_response_new();

/**
 * layrz_wifi_layrz_wifi_api_stop_scan_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to LayrzWifiApi.stopScan.
 *
 * Returns: a new #LayrzWifiLayrzWifiApiStopScanResponse
 */
LayrzWifiLayrzWifiApiStopScanResponse* layrz_wifi_layrz_wifi_api_stop_scan_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(LayrzWifiLayrzWifiApiEnsurePermissionsResponse, layrz_wifi_layrz_wifi_api_ensure_permissions_response, LAYRZ_WIFI, LAYRZ_WIFI_API_ENSURE_PERMISSIONS_RESPONSE, GObject)

/**
 * layrz_wifi_layrz_wifi_api_ensure_permissions_response_new:
 *
 * Creates a new response to LayrzWifiApi.ensurePermissions.
 *
 * Returns: a new #LayrzWifiLayrzWifiApiEnsurePermissionsResponse
 */
LayrzWifiLayrzWifiApiEnsurePermissionsResponse* layrz_wifi_layrz_wifi_api_ensure_permissions_response_new(LayrzWifiWifiPermissionStatus return_value);

/**
 * layrz_wifi_layrz_wifi_api_ensure_permissions_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to LayrzWifiApi.ensurePermissions.
 *
 * Returns: a new #LayrzWifiLayrzWifiApiEnsurePermissionsResponse
 */
LayrzWifiLayrzWifiApiEnsurePermissionsResponse* layrz_wifi_layrz_wifi_api_ensure_permissions_response_new_error(const gchar* code, const gchar* message, FlValue* details);

/**
 * LayrzWifiLayrzWifiApiVTable:
 *
 * Table of functions exposed by LayrzWifiApi to be implemented by the API provider.
 */
typedef struct {
  LayrzWifiLayrzWifiApiHasDiscoveryResponse* (*has_discovery)(gpointer user_data);
  LayrzWifiLayrzWifiApiHasCurrentSsidResponse* (*has_current_ssid)(gpointer user_data);
  LayrzWifiLayrzWifiApiCurrentSsidResponse* (*current_ssid)(gpointer user_data);
  LayrzWifiLayrzWifiApiStartScanResponse* (*start_scan)(gpointer user_data);
  LayrzWifiLayrzWifiApiStopScanResponse* (*stop_scan)(gpointer user_data);
  LayrzWifiLayrzWifiApiEnsurePermissionsResponse* (*ensure_permissions)(gpointer user_data);
} LayrzWifiLayrzWifiApiVTable;

/**
 * layrz_wifi_layrz_wifi_api_set_method_handlers:
 *
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 * @vtable: implementations of the methods in this API.
 * @user_data: (closure): user data to pass to the functions in @vtable.
 * @user_data_free_func: (allow-none): a function which gets called to free @user_data, or %NULL.
 *
 * Connects the method handlers in the LayrzWifiApi API.
 */
void layrz_wifi_layrz_wifi_api_set_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix, const LayrzWifiLayrzWifiApiVTable* vtable, gpointer user_data, GDestroyNotify user_data_free_func);

/**
 * layrz_wifi_layrz_wifi_api_clear_method_handlers:
 *
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 *
 * Clears the method handlers in the LayrzWifiApi API.
 */
void layrz_wifi_layrz_wifi_api_clear_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix);

G_DECLARE_FINAL_TYPE(LayrzWifiLayrzWifiEventsOnScanResultResponse, layrz_wifi_layrz_wifi_events_on_scan_result_response, LAYRZ_WIFI, LAYRZ_WIFI_EVENTS_ON_SCAN_RESULT_RESPONSE, GObject)

/**
 * layrz_wifi_layrz_wifi_events_on_scan_result_response_is_error:
 * @response: a #LayrzWifiLayrzWifiEventsOnScanResultResponse.
 *
 * Checks if a response to LayrzWifiEvents.onScanResult is an error.
 *
 * Returns: a %TRUE if this response is an error.
 */
gboolean layrz_wifi_layrz_wifi_events_on_scan_result_response_is_error(LayrzWifiLayrzWifiEventsOnScanResultResponse* response);

/**
 * layrz_wifi_layrz_wifi_events_on_scan_result_response_get_error_code:
 * @response: a #LayrzWifiLayrzWifiEventsOnScanResultResponse.
 *
 * Get the error code for this response.
 *
 * Returns: an error code or %NULL if not an error.
 */
const gchar* layrz_wifi_layrz_wifi_events_on_scan_result_response_get_error_code(LayrzWifiLayrzWifiEventsOnScanResultResponse* response);

/**
 * layrz_wifi_layrz_wifi_events_on_scan_result_response_get_error_message:
 * @response: a #LayrzWifiLayrzWifiEventsOnScanResultResponse.
 *
 * Get the error message for this response.
 *
 * Returns: an error message.
 */
const gchar* layrz_wifi_layrz_wifi_events_on_scan_result_response_get_error_message(LayrzWifiLayrzWifiEventsOnScanResultResponse* response);

/**
 * layrz_wifi_layrz_wifi_events_on_scan_result_response_get_error_details:
 * @response: a #LayrzWifiLayrzWifiEventsOnScanResultResponse.
 *
 * Get the error details for this response.
 *
 * Returns: (allow-none): an error details or %NULL.
 */
FlValue* layrz_wifi_layrz_wifi_events_on_scan_result_response_get_error_details(LayrzWifiLayrzWifiEventsOnScanResultResponse* response);

G_DECLARE_FINAL_TYPE(LayrzWifiLayrzWifiEventsOnScanCompleteResponse, layrz_wifi_layrz_wifi_events_on_scan_complete_response, LAYRZ_WIFI, LAYRZ_WIFI_EVENTS_ON_SCAN_COMPLETE_RESPONSE, GObject)

/**
 * layrz_wifi_layrz_wifi_events_on_scan_complete_response_is_error:
 * @response: a #LayrzWifiLayrzWifiEventsOnScanCompleteResponse.
 *
 * Checks if a response to LayrzWifiEvents.onScanComplete is an error.
 *
 * Returns: a %TRUE if this response is an error.
 */
gboolean layrz_wifi_layrz_wifi_events_on_scan_complete_response_is_error(LayrzWifiLayrzWifiEventsOnScanCompleteResponse* response);

/**
 * layrz_wifi_layrz_wifi_events_on_scan_complete_response_get_error_code:
 * @response: a #LayrzWifiLayrzWifiEventsOnScanCompleteResponse.
 *
 * Get the error code for this response.
 *
 * Returns: an error code or %NULL if not an error.
 */
const gchar* layrz_wifi_layrz_wifi_events_on_scan_complete_response_get_error_code(LayrzWifiLayrzWifiEventsOnScanCompleteResponse* response);

/**
 * layrz_wifi_layrz_wifi_events_on_scan_complete_response_get_error_message:
 * @response: a #LayrzWifiLayrzWifiEventsOnScanCompleteResponse.
 *
 * Get the error message for this response.
 *
 * Returns: an error message.
 */
const gchar* layrz_wifi_layrz_wifi_events_on_scan_complete_response_get_error_message(LayrzWifiLayrzWifiEventsOnScanCompleteResponse* response);

/**
 * layrz_wifi_layrz_wifi_events_on_scan_complete_response_get_error_details:
 * @response: a #LayrzWifiLayrzWifiEventsOnScanCompleteResponse.
 *
 * Get the error details for this response.
 *
 * Returns: (allow-none): an error details or %NULL.
 */
FlValue* layrz_wifi_layrz_wifi_events_on_scan_complete_response_get_error_details(LayrzWifiLayrzWifiEventsOnScanCompleteResponse* response);

G_DECLARE_FINAL_TYPE(LayrzWifiLayrzWifiEventsOnScanErrorResponse, layrz_wifi_layrz_wifi_events_on_scan_error_response, LAYRZ_WIFI, LAYRZ_WIFI_EVENTS_ON_SCAN_ERROR_RESPONSE, GObject)

/**
 * layrz_wifi_layrz_wifi_events_on_scan_error_response_is_error:
 * @response: a #LayrzWifiLayrzWifiEventsOnScanErrorResponse.
 *
 * Checks if a response to LayrzWifiEvents.onScanError is an error.
 *
 * Returns: a %TRUE if this response is an error.
 */
gboolean layrz_wifi_layrz_wifi_events_on_scan_error_response_is_error(LayrzWifiLayrzWifiEventsOnScanErrorResponse* response);

/**
 * layrz_wifi_layrz_wifi_events_on_scan_error_response_get_error_code:
 * @response: a #LayrzWifiLayrzWifiEventsOnScanErrorResponse.
 *
 * Get the error code for this response.
 *
 * Returns: an error code or %NULL if not an error.
 */
const gchar* layrz_wifi_layrz_wifi_events_on_scan_error_response_get_error_code(LayrzWifiLayrzWifiEventsOnScanErrorResponse* response);

/**
 * layrz_wifi_layrz_wifi_events_on_scan_error_response_get_error_message:
 * @response: a #LayrzWifiLayrzWifiEventsOnScanErrorResponse.
 *
 * Get the error message for this response.
 *
 * Returns: an error message.
 */
const gchar* layrz_wifi_layrz_wifi_events_on_scan_error_response_get_error_message(LayrzWifiLayrzWifiEventsOnScanErrorResponse* response);

/**
 * layrz_wifi_layrz_wifi_events_on_scan_error_response_get_error_details:
 * @response: a #LayrzWifiLayrzWifiEventsOnScanErrorResponse.
 *
 * Get the error details for this response.
 *
 * Returns: (allow-none): an error details or %NULL.
 */
FlValue* layrz_wifi_layrz_wifi_events_on_scan_error_response_get_error_details(LayrzWifiLayrzWifiEventsOnScanErrorResponse* response);

/**
 * LayrzWifiLayrzWifiEvents:
 *
 */

G_DECLARE_FINAL_TYPE(LayrzWifiLayrzWifiEvents, layrz_wifi_layrz_wifi_events, LAYRZ_WIFI, LAYRZ_WIFI_EVENTS, GObject)

/**
 * layrz_wifi_layrz_wifi_events_new:
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 *
 * Creates a new object to access the LayrzWifiEvents API.
 *
 * Returns: a new #LayrzWifiLayrzWifiEvents
 */
LayrzWifiLayrzWifiEvents* layrz_wifi_layrz_wifi_events_new(FlBinaryMessenger* messenger, const gchar* suffix);

/**
 * layrz_wifi_layrz_wifi_events_on_scan_result:
 * @api: a #LayrzWifiLayrzWifiEvents.
 * @network: parameter for this method.
 * @cancellable: (allow-none): a #GCancellable or %NULL.
 * @callback: (scope async): (allow-none): a #GAsyncReadyCallback to call when the call is complete or %NULL to ignore the response.
 * @user_data: (closure): user data to pass to @callback.
 *
 */
void layrz_wifi_layrz_wifi_events_on_scan_result(LayrzWifiLayrzWifiEvents* api, LayrzWifiWifiNetwork* network, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);

/**
 * layrz_wifi_layrz_wifi_events_on_scan_result_finish:
 * @api: a #LayrzWifiLayrzWifiEvents.
 * @result: a #GAsyncResult.
 * @error: (allow-none): #GError location to store the error occurring, or %NULL to ignore.
 *
 * Completes a layrz_wifi_layrz_wifi_events_on_scan_result() call.
 *
 * Returns: a #LayrzWifiLayrzWifiEventsOnScanResultResponse or %NULL on error.
 */
LayrzWifiLayrzWifiEventsOnScanResultResponse* layrz_wifi_layrz_wifi_events_on_scan_result_finish(LayrzWifiLayrzWifiEvents* api, GAsyncResult* result, GError** error);

/**
 * layrz_wifi_layrz_wifi_events_on_scan_complete:
 * @api: a #LayrzWifiLayrzWifiEvents.
 * @cancellable: (allow-none): a #GCancellable or %NULL.
 * @callback: (scope async): (allow-none): a #GAsyncReadyCallback to call when the call is complete or %NULL to ignore the response.
 * @user_data: (closure): user data to pass to @callback.
 *
 */
void layrz_wifi_layrz_wifi_events_on_scan_complete(LayrzWifiLayrzWifiEvents* api, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);

/**
 * layrz_wifi_layrz_wifi_events_on_scan_complete_finish:
 * @api: a #LayrzWifiLayrzWifiEvents.
 * @result: a #GAsyncResult.
 * @error: (allow-none): #GError location to store the error occurring, or %NULL to ignore.
 *
 * Completes a layrz_wifi_layrz_wifi_events_on_scan_complete() call.
 *
 * Returns: a #LayrzWifiLayrzWifiEventsOnScanCompleteResponse or %NULL on error.
 */
LayrzWifiLayrzWifiEventsOnScanCompleteResponse* layrz_wifi_layrz_wifi_events_on_scan_complete_finish(LayrzWifiLayrzWifiEvents* api, GAsyncResult* result, GError** error);

/**
 * layrz_wifi_layrz_wifi_events_on_scan_error:
 * @api: a #LayrzWifiLayrzWifiEvents.
 * @message: parameter for this method.
 * @cancellable: (allow-none): a #GCancellable or %NULL.
 * @callback: (scope async): (allow-none): a #GAsyncReadyCallback to call when the call is complete or %NULL to ignore the response.
 * @user_data: (closure): user data to pass to @callback.
 *
 */
void layrz_wifi_layrz_wifi_events_on_scan_error(LayrzWifiLayrzWifiEvents* api, const gchar* message, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);

/**
 * layrz_wifi_layrz_wifi_events_on_scan_error_finish:
 * @api: a #LayrzWifiLayrzWifiEvents.
 * @result: a #GAsyncResult.
 * @error: (allow-none): #GError location to store the error occurring, or %NULL to ignore.
 *
 * Completes a layrz_wifi_layrz_wifi_events_on_scan_error() call.
 *
 * Returns: a #LayrzWifiLayrzWifiEventsOnScanErrorResponse or %NULL on error.
 */
LayrzWifiLayrzWifiEventsOnScanErrorResponse* layrz_wifi_layrz_wifi_events_on_scan_error_finish(LayrzWifiLayrzWifiEvents* api, GAsyncResult* result, GError** error);

G_END_DECLS

#endif  // PIGEON_MESSAGES_G_H_
