// Copyright 2024 Golden M, Inc. All rights reserved.
// Use of this source code is governed by an MIT-style license that can be
// found in the LICENSE file.
// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#include "messages.g.h"

struct _LayrzWifiWifiNetwork {
  GObject parent_instance;

  gchar* ssid;
  gchar* bssid;
  int64_t* signal_dbm;
  int64_t* frequency_mhz;
  LayrzWifiWifiSecurity security;
  gboolean is_hidden;
};

G_DEFINE_TYPE(LayrzWifiWifiNetwork, layrz_wifi_wifi_network, G_TYPE_OBJECT)

static void layrz_wifi_wifi_network_dispose(GObject* object) {
  LayrzWifiWifiNetwork* self = LAYRZ_WIFI_WIFI_NETWORK(object);
  g_clear_pointer(&self->ssid, g_free);
  g_clear_pointer(&self->bssid, g_free);
  g_clear_pointer(&self->signal_dbm, g_free);
  g_clear_pointer(&self->frequency_mhz, g_free);
  G_OBJECT_CLASS(layrz_wifi_wifi_network_parent_class)->dispose(object);
}

static void layrz_wifi_wifi_network_init(LayrzWifiWifiNetwork* self) {
}

static void layrz_wifi_wifi_network_class_init(LayrzWifiWifiNetworkClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = layrz_wifi_wifi_network_dispose;
}

LayrzWifiWifiNetwork* layrz_wifi_wifi_network_new(const gchar* ssid, const gchar* bssid, int64_t* signal_dbm, int64_t* frequency_mhz, LayrzWifiWifiSecurity security, gboolean is_hidden) {
  LayrzWifiWifiNetwork* self = LAYRZ_WIFI_WIFI_NETWORK(g_object_new(layrz_wifi_wifi_network_get_type(), nullptr));
  self->ssid = g_strdup(ssid);
  if (bssid != nullptr) {
    self->bssid = g_strdup(bssid);
  }
  else {
    self->bssid = nullptr;
  }
  if (signal_dbm != nullptr) {
    self->signal_dbm = static_cast<int64_t*>(malloc(sizeof(int64_t)));
    *self->signal_dbm = *signal_dbm;
  }
  else {
    self->signal_dbm = nullptr;
  }
  if (frequency_mhz != nullptr) {
    self->frequency_mhz = static_cast<int64_t*>(malloc(sizeof(int64_t)));
    *self->frequency_mhz = *frequency_mhz;
  }
  else {
    self->frequency_mhz = nullptr;
  }
  self->security = security;
  self->is_hidden = is_hidden;
  return self;
}

const gchar* layrz_wifi_wifi_network_get_ssid(LayrzWifiWifiNetwork* self) {
  g_return_val_if_fail(LAYRZ_WIFI_IS_WIFI_NETWORK(self), nullptr);
  return self->ssid;
}

const gchar* layrz_wifi_wifi_network_get_bssid(LayrzWifiWifiNetwork* self) {
  g_return_val_if_fail(LAYRZ_WIFI_IS_WIFI_NETWORK(self), nullptr);
  return self->bssid;
}

int64_t* layrz_wifi_wifi_network_get_signal_dbm(LayrzWifiWifiNetwork* self) {
  g_return_val_if_fail(LAYRZ_WIFI_IS_WIFI_NETWORK(self), nullptr);
  return self->signal_dbm;
}

int64_t* layrz_wifi_wifi_network_get_frequency_mhz(LayrzWifiWifiNetwork* self) {
  g_return_val_if_fail(LAYRZ_WIFI_IS_WIFI_NETWORK(self), nullptr);
  return self->frequency_mhz;
}

LayrzWifiWifiSecurity layrz_wifi_wifi_network_get_security(LayrzWifiWifiNetwork* self) {
  g_return_val_if_fail(LAYRZ_WIFI_IS_WIFI_NETWORK(self), static_cast<LayrzWifiWifiSecurity>(0));
  return self->security;
}

gboolean layrz_wifi_wifi_network_get_is_hidden(LayrzWifiWifiNetwork* self) {
  g_return_val_if_fail(LAYRZ_WIFI_IS_WIFI_NETWORK(self), FALSE);
  return self->is_hidden;
}

static FlValue* layrz_wifi_wifi_network_to_list(LayrzWifiWifiNetwork* self) {
  FlValue* values = fl_value_new_list();
  fl_value_append_take(values, fl_value_new_string(self->ssid));
  fl_value_append_take(values, self->bssid != nullptr ? fl_value_new_string(self->bssid) : fl_value_new_null());
  fl_value_append_take(values, self->signal_dbm != nullptr ? fl_value_new_int(*self->signal_dbm) : fl_value_new_null());
  fl_value_append_take(values, self->frequency_mhz != nullptr ? fl_value_new_int(*self->frequency_mhz) : fl_value_new_null());
  fl_value_append_take(values, fl_value_new_custom(129, fl_value_new_int(self->security), (GDestroyNotify)fl_value_unref));
  fl_value_append_take(values, fl_value_new_bool(self->is_hidden));
  return values;
}

static LayrzWifiWifiNetwork* layrz_wifi_wifi_network_new_from_list(FlValue* values) {
  FlValue* value0 = fl_value_get_list_value(values, 0);
  const gchar* ssid = fl_value_get_string(value0);
  FlValue* value1 = fl_value_get_list_value(values, 1);
  const gchar* bssid = nullptr;
  if (fl_value_get_type(value1) != FL_VALUE_TYPE_NULL) {
    bssid = fl_value_get_string(value1);
  }
  FlValue* value2 = fl_value_get_list_value(values, 2);
  int64_t* signal_dbm = nullptr;
  int64_t signal_dbm_value;
  if (fl_value_get_type(value2) != FL_VALUE_TYPE_NULL) {
    signal_dbm_value = fl_value_get_int(value2);
    signal_dbm = &signal_dbm_value;
  }
  FlValue* value3 = fl_value_get_list_value(values, 3);
  int64_t* frequency_mhz = nullptr;
  int64_t frequency_mhz_value;
  if (fl_value_get_type(value3) != FL_VALUE_TYPE_NULL) {
    frequency_mhz_value = fl_value_get_int(value3);
    frequency_mhz = &frequency_mhz_value;
  }
  FlValue* value4 = fl_value_get_list_value(values, 4);
  LayrzWifiWifiSecurity security = static_cast<LayrzWifiWifiSecurity>(fl_value_get_int(reinterpret_cast<FlValue*>(const_cast<gpointer>(fl_value_get_custom_value(value4)))));
  FlValue* value5 = fl_value_get_list_value(values, 5);
  gboolean is_hidden = fl_value_get_bool(value5);
  return layrz_wifi_wifi_network_new(ssid, bssid, signal_dbm, frequency_mhz, security, is_hidden);
}

struct _LayrzWifiMessageCodec {
  FlStandardMessageCodec parent_instance;

};

G_DEFINE_TYPE(LayrzWifiMessageCodec, layrz_wifi_message_codec, fl_standard_message_codec_get_type())

static gboolean layrz_wifi_message_codec_write_layrz_wifi_wifi_security(FlStandardMessageCodec* codec, GByteArray* buffer, FlValue* value, GError** error) {
  uint8_t type = 129;
  g_byte_array_append(buffer, &type, sizeof(uint8_t));
  return fl_standard_message_codec_write_value(codec, buffer, value, error);
}

static gboolean layrz_wifi_message_codec_write_layrz_wifi_wifi_permission_status(FlStandardMessageCodec* codec, GByteArray* buffer, FlValue* value, GError** error) {
  uint8_t type = 130;
  g_byte_array_append(buffer, &type, sizeof(uint8_t));
  return fl_standard_message_codec_write_value(codec, buffer, value, error);
}

static gboolean layrz_wifi_message_codec_write_layrz_wifi_wifi_network(FlStandardMessageCodec* codec, GByteArray* buffer, LayrzWifiWifiNetwork* value, GError** error) {
  uint8_t type = 131;
  g_byte_array_append(buffer, &type, sizeof(uint8_t));
  g_autoptr(FlValue) values = layrz_wifi_wifi_network_to_list(value);
  return fl_standard_message_codec_write_value(codec, buffer, values, error);
}

static gboolean layrz_wifi_message_codec_write_value(FlStandardMessageCodec* codec, GByteArray* buffer, FlValue* value, GError** error) {
  if (fl_value_get_type(value) == FL_VALUE_TYPE_CUSTOM) {
    switch (fl_value_get_custom_type(value)) {
      case 129:
        return layrz_wifi_message_codec_write_layrz_wifi_wifi_security(codec, buffer, reinterpret_cast<FlValue*>(const_cast<gpointer>(fl_value_get_custom_value(value))), error);
      case 130:
        return layrz_wifi_message_codec_write_layrz_wifi_wifi_permission_status(codec, buffer, reinterpret_cast<FlValue*>(const_cast<gpointer>(fl_value_get_custom_value(value))), error);
      case 131:
        return layrz_wifi_message_codec_write_layrz_wifi_wifi_network(codec, buffer, LAYRZ_WIFI_WIFI_NETWORK(fl_value_get_custom_value_object(value)), error);
    }
  }

  return FL_STANDARD_MESSAGE_CODEC_CLASS(layrz_wifi_message_codec_parent_class)->write_value(codec, buffer, value, error);
}

static FlValue* layrz_wifi_message_codec_read_layrz_wifi_wifi_security(FlStandardMessageCodec* codec, GBytes* buffer, size_t* offset, GError** error) {
  return fl_value_new_custom(129, fl_standard_message_codec_read_value(codec, buffer, offset, error), (GDestroyNotify)fl_value_unref);
}

static FlValue* layrz_wifi_message_codec_read_layrz_wifi_wifi_permission_status(FlStandardMessageCodec* codec, GBytes* buffer, size_t* offset, GError** error) {
  return fl_value_new_custom(130, fl_standard_message_codec_read_value(codec, buffer, offset, error), (GDestroyNotify)fl_value_unref);
}

static FlValue* layrz_wifi_message_codec_read_layrz_wifi_wifi_network(FlStandardMessageCodec* codec, GBytes* buffer, size_t* offset, GError** error) {
  g_autoptr(FlValue) values = fl_standard_message_codec_read_value(codec, buffer, offset, error);
  if (values == nullptr) {
    return nullptr;
  }

  g_autoptr(LayrzWifiWifiNetwork) value = layrz_wifi_wifi_network_new_from_list(values);
  if (value == nullptr) {
    g_set_error(error, FL_MESSAGE_CODEC_ERROR, FL_MESSAGE_CODEC_ERROR_FAILED, "Invalid data received for MessageData");
    return nullptr;
  }

  return fl_value_new_custom_object(131, G_OBJECT(value));
}

static FlValue* layrz_wifi_message_codec_read_value_of_type(FlStandardMessageCodec* codec, GBytes* buffer, size_t* offset, int type, GError** error) {
  switch (type) {
    case 129:
      return layrz_wifi_message_codec_read_layrz_wifi_wifi_security(codec, buffer, offset, error);
    case 130:
      return layrz_wifi_message_codec_read_layrz_wifi_wifi_permission_status(codec, buffer, offset, error);
    case 131:
      return layrz_wifi_message_codec_read_layrz_wifi_wifi_network(codec, buffer, offset, error);
    default:
      return FL_STANDARD_MESSAGE_CODEC_CLASS(layrz_wifi_message_codec_parent_class)->read_value_of_type(codec, buffer, offset, type, error);
  }
}

static void layrz_wifi_message_codec_init(LayrzWifiMessageCodec* self) {
}

static void layrz_wifi_message_codec_class_init(LayrzWifiMessageCodecClass* klass) {
  FL_STANDARD_MESSAGE_CODEC_CLASS(klass)->write_value = layrz_wifi_message_codec_write_value;
  FL_STANDARD_MESSAGE_CODEC_CLASS(klass)->read_value_of_type = layrz_wifi_message_codec_read_value_of_type;
}

static LayrzWifiMessageCodec* layrz_wifi_message_codec_new() {
  LayrzWifiMessageCodec* self = LAYRZ_WIFI_MESSAGE_CODEC(g_object_new(layrz_wifi_message_codec_get_type(), nullptr));
  return self;
}

struct _LayrzWifiLayrzWifiApiHasDiscoveryResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(LayrzWifiLayrzWifiApiHasDiscoveryResponse, layrz_wifi_layrz_wifi_api_has_discovery_response, G_TYPE_OBJECT)

static void layrz_wifi_layrz_wifi_api_has_discovery_response_dispose(GObject* object) {
  LayrzWifiLayrzWifiApiHasDiscoveryResponse* self = LAYRZ_WIFI_LAYRZ_WIFI_API_HAS_DISCOVERY_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(layrz_wifi_layrz_wifi_api_has_discovery_response_parent_class)->dispose(object);
}

static void layrz_wifi_layrz_wifi_api_has_discovery_response_init(LayrzWifiLayrzWifiApiHasDiscoveryResponse* self) {
}

static void layrz_wifi_layrz_wifi_api_has_discovery_response_class_init(LayrzWifiLayrzWifiApiHasDiscoveryResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = layrz_wifi_layrz_wifi_api_has_discovery_response_dispose;
}

LayrzWifiLayrzWifiApiHasDiscoveryResponse* layrz_wifi_layrz_wifi_api_has_discovery_response_new(gboolean return_value) {
  LayrzWifiLayrzWifiApiHasDiscoveryResponse* self = LAYRZ_WIFI_LAYRZ_WIFI_API_HAS_DISCOVERY_RESPONSE(g_object_new(layrz_wifi_layrz_wifi_api_has_discovery_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_bool(return_value));
  return self;
}

LayrzWifiLayrzWifiApiHasDiscoveryResponse* layrz_wifi_layrz_wifi_api_has_discovery_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  LayrzWifiLayrzWifiApiHasDiscoveryResponse* self = LAYRZ_WIFI_LAYRZ_WIFI_API_HAS_DISCOVERY_RESPONSE(g_object_new(layrz_wifi_layrz_wifi_api_has_discovery_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

struct _LayrzWifiLayrzWifiApiHasCurrentSsidResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(LayrzWifiLayrzWifiApiHasCurrentSsidResponse, layrz_wifi_layrz_wifi_api_has_current_ssid_response, G_TYPE_OBJECT)

static void layrz_wifi_layrz_wifi_api_has_current_ssid_response_dispose(GObject* object) {
  LayrzWifiLayrzWifiApiHasCurrentSsidResponse* self = LAYRZ_WIFI_LAYRZ_WIFI_API_HAS_CURRENT_SSID_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(layrz_wifi_layrz_wifi_api_has_current_ssid_response_parent_class)->dispose(object);
}

static void layrz_wifi_layrz_wifi_api_has_current_ssid_response_init(LayrzWifiLayrzWifiApiHasCurrentSsidResponse* self) {
}

static void layrz_wifi_layrz_wifi_api_has_current_ssid_response_class_init(LayrzWifiLayrzWifiApiHasCurrentSsidResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = layrz_wifi_layrz_wifi_api_has_current_ssid_response_dispose;
}

LayrzWifiLayrzWifiApiHasCurrentSsidResponse* layrz_wifi_layrz_wifi_api_has_current_ssid_response_new(gboolean return_value) {
  LayrzWifiLayrzWifiApiHasCurrentSsidResponse* self = LAYRZ_WIFI_LAYRZ_WIFI_API_HAS_CURRENT_SSID_RESPONSE(g_object_new(layrz_wifi_layrz_wifi_api_has_current_ssid_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_bool(return_value));
  return self;
}

LayrzWifiLayrzWifiApiHasCurrentSsidResponse* layrz_wifi_layrz_wifi_api_has_current_ssid_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  LayrzWifiLayrzWifiApiHasCurrentSsidResponse* self = LAYRZ_WIFI_LAYRZ_WIFI_API_HAS_CURRENT_SSID_RESPONSE(g_object_new(layrz_wifi_layrz_wifi_api_has_current_ssid_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

struct _LayrzWifiLayrzWifiApiCurrentSsidResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(LayrzWifiLayrzWifiApiCurrentSsidResponse, layrz_wifi_layrz_wifi_api_current_ssid_response, G_TYPE_OBJECT)

static void layrz_wifi_layrz_wifi_api_current_ssid_response_dispose(GObject* object) {
  LayrzWifiLayrzWifiApiCurrentSsidResponse* self = LAYRZ_WIFI_LAYRZ_WIFI_API_CURRENT_SSID_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(layrz_wifi_layrz_wifi_api_current_ssid_response_parent_class)->dispose(object);
}

static void layrz_wifi_layrz_wifi_api_current_ssid_response_init(LayrzWifiLayrzWifiApiCurrentSsidResponse* self) {
}

static void layrz_wifi_layrz_wifi_api_current_ssid_response_class_init(LayrzWifiLayrzWifiApiCurrentSsidResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = layrz_wifi_layrz_wifi_api_current_ssid_response_dispose;
}

LayrzWifiLayrzWifiApiCurrentSsidResponse* layrz_wifi_layrz_wifi_api_current_ssid_response_new(const gchar* return_value) {
  LayrzWifiLayrzWifiApiCurrentSsidResponse* self = LAYRZ_WIFI_LAYRZ_WIFI_API_CURRENT_SSID_RESPONSE(g_object_new(layrz_wifi_layrz_wifi_api_current_ssid_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, return_value != nullptr ? fl_value_new_string(return_value) : fl_value_new_null());
  return self;
}

LayrzWifiLayrzWifiApiCurrentSsidResponse* layrz_wifi_layrz_wifi_api_current_ssid_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  LayrzWifiLayrzWifiApiCurrentSsidResponse* self = LAYRZ_WIFI_LAYRZ_WIFI_API_CURRENT_SSID_RESPONSE(g_object_new(layrz_wifi_layrz_wifi_api_current_ssid_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

struct _LayrzWifiLayrzWifiApiScanResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(LayrzWifiLayrzWifiApiScanResponse, layrz_wifi_layrz_wifi_api_scan_response, G_TYPE_OBJECT)

static void layrz_wifi_layrz_wifi_api_scan_response_dispose(GObject* object) {
  LayrzWifiLayrzWifiApiScanResponse* self = LAYRZ_WIFI_LAYRZ_WIFI_API_SCAN_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(layrz_wifi_layrz_wifi_api_scan_response_parent_class)->dispose(object);
}

static void layrz_wifi_layrz_wifi_api_scan_response_init(LayrzWifiLayrzWifiApiScanResponse* self) {
}

static void layrz_wifi_layrz_wifi_api_scan_response_class_init(LayrzWifiLayrzWifiApiScanResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = layrz_wifi_layrz_wifi_api_scan_response_dispose;
}

LayrzWifiLayrzWifiApiScanResponse* layrz_wifi_layrz_wifi_api_scan_response_new(FlValue* return_value) {
  LayrzWifiLayrzWifiApiScanResponse* self = LAYRZ_WIFI_LAYRZ_WIFI_API_SCAN_RESPONSE(g_object_new(layrz_wifi_layrz_wifi_api_scan_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_ref(return_value));
  return self;
}

LayrzWifiLayrzWifiApiScanResponse* layrz_wifi_layrz_wifi_api_scan_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  LayrzWifiLayrzWifiApiScanResponse* self = LAYRZ_WIFI_LAYRZ_WIFI_API_SCAN_RESPONSE(g_object_new(layrz_wifi_layrz_wifi_api_scan_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

struct _LayrzWifiLayrzWifiApiEnsurePermissionsResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(LayrzWifiLayrzWifiApiEnsurePermissionsResponse, layrz_wifi_layrz_wifi_api_ensure_permissions_response, G_TYPE_OBJECT)

static void layrz_wifi_layrz_wifi_api_ensure_permissions_response_dispose(GObject* object) {
  LayrzWifiLayrzWifiApiEnsurePermissionsResponse* self = LAYRZ_WIFI_LAYRZ_WIFI_API_ENSURE_PERMISSIONS_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(layrz_wifi_layrz_wifi_api_ensure_permissions_response_parent_class)->dispose(object);
}

static void layrz_wifi_layrz_wifi_api_ensure_permissions_response_init(LayrzWifiLayrzWifiApiEnsurePermissionsResponse* self) {
}

static void layrz_wifi_layrz_wifi_api_ensure_permissions_response_class_init(LayrzWifiLayrzWifiApiEnsurePermissionsResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = layrz_wifi_layrz_wifi_api_ensure_permissions_response_dispose;
}

LayrzWifiLayrzWifiApiEnsurePermissionsResponse* layrz_wifi_layrz_wifi_api_ensure_permissions_response_new(LayrzWifiWifiPermissionStatus return_value) {
  LayrzWifiLayrzWifiApiEnsurePermissionsResponse* self = LAYRZ_WIFI_LAYRZ_WIFI_API_ENSURE_PERMISSIONS_RESPONSE(g_object_new(layrz_wifi_layrz_wifi_api_ensure_permissions_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_custom(130, fl_value_new_int(return_value), (GDestroyNotify)fl_value_unref));
  return self;
}

LayrzWifiLayrzWifiApiEnsurePermissionsResponse* layrz_wifi_layrz_wifi_api_ensure_permissions_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  LayrzWifiLayrzWifiApiEnsurePermissionsResponse* self = LAYRZ_WIFI_LAYRZ_WIFI_API_ENSURE_PERMISSIONS_RESPONSE(g_object_new(layrz_wifi_layrz_wifi_api_ensure_permissions_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

struct _LayrzWifiLayrzWifiApi {
  GObject parent_instance;

  const LayrzWifiLayrzWifiApiVTable* vtable;
  gpointer user_data;
  GDestroyNotify user_data_free_func;
};

G_DEFINE_TYPE(LayrzWifiLayrzWifiApi, layrz_wifi_layrz_wifi_api, G_TYPE_OBJECT)

static void layrz_wifi_layrz_wifi_api_dispose(GObject* object) {
  LayrzWifiLayrzWifiApi* self = LAYRZ_WIFI_LAYRZ_WIFI_API(object);
  if (self->user_data != nullptr) {
    self->user_data_free_func(self->user_data);
  }
  self->user_data = nullptr;
  G_OBJECT_CLASS(layrz_wifi_layrz_wifi_api_parent_class)->dispose(object);
}

static void layrz_wifi_layrz_wifi_api_init(LayrzWifiLayrzWifiApi* self) {
}

static void layrz_wifi_layrz_wifi_api_class_init(LayrzWifiLayrzWifiApiClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = layrz_wifi_layrz_wifi_api_dispose;
}

static LayrzWifiLayrzWifiApi* layrz_wifi_layrz_wifi_api_new(const LayrzWifiLayrzWifiApiVTable* vtable, gpointer user_data, GDestroyNotify user_data_free_func) {
  LayrzWifiLayrzWifiApi* self = LAYRZ_WIFI_LAYRZ_WIFI_API(g_object_new(layrz_wifi_layrz_wifi_api_get_type(), nullptr));
  self->vtable = vtable;
  self->user_data = user_data;
  self->user_data_free_func = user_data_free_func;
  return self;
}

static void layrz_wifi_layrz_wifi_api_has_discovery_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  LayrzWifiLayrzWifiApi* self = LAYRZ_WIFI_LAYRZ_WIFI_API(user_data);

  if (self->vtable == nullptr || self->vtable->has_discovery == nullptr) {
    return;
  }

  g_autoptr(LayrzWifiLayrzWifiApiHasDiscoveryResponse) response = self->vtable->has_discovery(self->user_data);
  if (response == nullptr) {
    g_warning("No response returned to %s.%s", "LayrzWifiApi", "hasDiscovery");
    return;
  }

  g_autoptr(GError) error = NULL;
  if (!fl_basic_message_channel_respond(channel, response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "LayrzWifiApi", "hasDiscovery", error->message);
  }
}

static void layrz_wifi_layrz_wifi_api_has_current_ssid_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  LayrzWifiLayrzWifiApi* self = LAYRZ_WIFI_LAYRZ_WIFI_API(user_data);

  if (self->vtable == nullptr || self->vtable->has_current_ssid == nullptr) {
    return;
  }

  g_autoptr(LayrzWifiLayrzWifiApiHasCurrentSsidResponse) response = self->vtable->has_current_ssid(self->user_data);
  if (response == nullptr) {
    g_warning("No response returned to %s.%s", "LayrzWifiApi", "hasCurrentSsid");
    return;
  }

  g_autoptr(GError) error = NULL;
  if (!fl_basic_message_channel_respond(channel, response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "LayrzWifiApi", "hasCurrentSsid", error->message);
  }
}

static void layrz_wifi_layrz_wifi_api_current_ssid_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  LayrzWifiLayrzWifiApi* self = LAYRZ_WIFI_LAYRZ_WIFI_API(user_data);

  if (self->vtable == nullptr || self->vtable->current_ssid == nullptr) {
    return;
  }

  g_autoptr(LayrzWifiLayrzWifiApiCurrentSsidResponse) response = self->vtable->current_ssid(self->user_data);
  if (response == nullptr) {
    g_warning("No response returned to %s.%s", "LayrzWifiApi", "currentSsid");
    return;
  }

  g_autoptr(GError) error = NULL;
  if (!fl_basic_message_channel_respond(channel, response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "LayrzWifiApi", "currentSsid", error->message);
  }
}

static void layrz_wifi_layrz_wifi_api_scan_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  LayrzWifiLayrzWifiApi* self = LAYRZ_WIFI_LAYRZ_WIFI_API(user_data);

  if (self->vtable == nullptr || self->vtable->scan == nullptr) {
    return;
  }

  g_autoptr(LayrzWifiLayrzWifiApiScanResponse) response = self->vtable->scan(self->user_data);
  if (response == nullptr) {
    g_warning("No response returned to %s.%s", "LayrzWifiApi", "scan");
    return;
  }

  g_autoptr(GError) error = NULL;
  if (!fl_basic_message_channel_respond(channel, response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "LayrzWifiApi", "scan", error->message);
  }
}

static void layrz_wifi_layrz_wifi_api_ensure_permissions_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  LayrzWifiLayrzWifiApi* self = LAYRZ_WIFI_LAYRZ_WIFI_API(user_data);

  if (self->vtable == nullptr || self->vtable->ensure_permissions == nullptr) {
    return;
  }

  g_autoptr(LayrzWifiLayrzWifiApiEnsurePermissionsResponse) response = self->vtable->ensure_permissions(self->user_data);
  if (response == nullptr) {
    g_warning("No response returned to %s.%s", "LayrzWifiApi", "ensurePermissions");
    return;
  }

  g_autoptr(GError) error = NULL;
  if (!fl_basic_message_channel_respond(channel, response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "LayrzWifiApi", "ensurePermissions", error->message);
  }
}

void layrz_wifi_layrz_wifi_api_set_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix, const LayrzWifiLayrzWifiApiVTable* vtable, gpointer user_data, GDestroyNotify user_data_free_func) {
  g_autofree gchar* dot_suffix = suffix != nullptr ? g_strdup_printf(".%s", suffix) : g_strdup("");
  g_autoptr(LayrzWifiLayrzWifiApi) api_data = layrz_wifi_layrz_wifi_api_new(vtable, user_data, user_data_free_func);

  g_autoptr(LayrzWifiMessageCodec) codec = layrz_wifi_message_codec_new();
  g_autofree gchar* has_discovery_channel_name = g_strdup_printf("dev.flutter.pigeon.layrz_wifi.LayrzWifiApi.hasDiscovery%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) has_discovery_channel = fl_basic_message_channel_new(messenger, has_discovery_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(has_discovery_channel, layrz_wifi_layrz_wifi_api_has_discovery_cb, g_object_ref(api_data), g_object_unref);
  g_autofree gchar* has_current_ssid_channel_name = g_strdup_printf("dev.flutter.pigeon.layrz_wifi.LayrzWifiApi.hasCurrentSsid%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) has_current_ssid_channel = fl_basic_message_channel_new(messenger, has_current_ssid_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(has_current_ssid_channel, layrz_wifi_layrz_wifi_api_has_current_ssid_cb, g_object_ref(api_data), g_object_unref);
  g_autofree gchar* current_ssid_channel_name = g_strdup_printf("dev.flutter.pigeon.layrz_wifi.LayrzWifiApi.currentSsid%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) current_ssid_channel = fl_basic_message_channel_new(messenger, current_ssid_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(current_ssid_channel, layrz_wifi_layrz_wifi_api_current_ssid_cb, g_object_ref(api_data), g_object_unref);
  g_autofree gchar* scan_channel_name = g_strdup_printf("dev.flutter.pigeon.layrz_wifi.LayrzWifiApi.scan%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) scan_channel = fl_basic_message_channel_new(messenger, scan_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(scan_channel, layrz_wifi_layrz_wifi_api_scan_cb, g_object_ref(api_data), g_object_unref);
  g_autofree gchar* ensure_permissions_channel_name = g_strdup_printf("dev.flutter.pigeon.layrz_wifi.LayrzWifiApi.ensurePermissions%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) ensure_permissions_channel = fl_basic_message_channel_new(messenger, ensure_permissions_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(ensure_permissions_channel, layrz_wifi_layrz_wifi_api_ensure_permissions_cb, g_object_ref(api_data), g_object_unref);
}

void layrz_wifi_layrz_wifi_api_clear_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix) {
  g_autofree gchar* dot_suffix = suffix != nullptr ? g_strdup_printf(".%s", suffix) : g_strdup("");

  g_autoptr(LayrzWifiMessageCodec) codec = layrz_wifi_message_codec_new();
  g_autofree gchar* has_discovery_channel_name = g_strdup_printf("dev.flutter.pigeon.layrz_wifi.LayrzWifiApi.hasDiscovery%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) has_discovery_channel = fl_basic_message_channel_new(messenger, has_discovery_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(has_discovery_channel, nullptr, nullptr, nullptr);
  g_autofree gchar* has_current_ssid_channel_name = g_strdup_printf("dev.flutter.pigeon.layrz_wifi.LayrzWifiApi.hasCurrentSsid%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) has_current_ssid_channel = fl_basic_message_channel_new(messenger, has_current_ssid_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(has_current_ssid_channel, nullptr, nullptr, nullptr);
  g_autofree gchar* current_ssid_channel_name = g_strdup_printf("dev.flutter.pigeon.layrz_wifi.LayrzWifiApi.currentSsid%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) current_ssid_channel = fl_basic_message_channel_new(messenger, current_ssid_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(current_ssid_channel, nullptr, nullptr, nullptr);
  g_autofree gchar* scan_channel_name = g_strdup_printf("dev.flutter.pigeon.layrz_wifi.LayrzWifiApi.scan%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) scan_channel = fl_basic_message_channel_new(messenger, scan_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(scan_channel, nullptr, nullptr, nullptr);
  g_autofree gchar* ensure_permissions_channel_name = g_strdup_printf("dev.flutter.pigeon.layrz_wifi.LayrzWifiApi.ensurePermissions%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) ensure_permissions_channel = fl_basic_message_channel_new(messenger, ensure_permissions_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(ensure_permissions_channel, nullptr, nullptr, nullptr);
}
