// Copyright 2026 Golden M, Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the “Software”), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#include "messages.g.h"

struct _LayrzWifiWifiNetwork {
  GObject parent_instance;

  gchar* ssid;
  gchar* bssid;
  int64_t* signal_dbm;
  int64_t* frequency_mhz;
  LayrzWifiWifiSecurity security;
  gboolean is_hidden;
};

G_DEFINE_TYPE(LayrzWifiWifiNetwork, layrz_wifi_wifi_network, G_TYPE_OBJECT)

static void layrz_wifi_wifi_network_dispose(GObject* object) {
  LayrzWifiWifiNetwork* self = LAYRZ_WIFI_WIFI_NETWORK(object);
  g_clear_pointer(&self->ssid, g_free);
  g_clear_pointer(&self->bssid, g_free);
  g_clear_pointer(&self->signal_dbm, g_free);
  g_clear_pointer(&self->frequency_mhz, g_free);
  G_OBJECT_CLASS(layrz_wifi_wifi_network_parent_class)->dispose(object);
}

static void layrz_wifi_wifi_network_init(LayrzWifiWifiNetwork* self) {
}

static void layrz_wifi_wifi_network_class_init(LayrzWifiWifiNetworkClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = layrz_wifi_wifi_network_dispose;
}

LayrzWifiWifiNetwork* layrz_wifi_wifi_network_new(const gchar* ssid, const gchar* bssid, int64_t* signal_dbm, int64_t* frequency_mhz, LayrzWifiWifiSecurity security, gboolean is_hidden) {
  LayrzWifiWifiNetwork* self = LAYRZ_WIFI_WIFI_NETWORK(g_object_new(layrz_wifi_wifi_network_get_type(), nullptr));
  self->ssid = g_strdup(ssid);
  if (bssid != nullptr) {
    self->bssid = g_strdup(bssid);
  }
  else {
    self->bssid = nullptr;
  }
  if (signal_dbm != nullptr) {
    self->signal_dbm = static_cast<int64_t*>(malloc(sizeof(int64_t)));
    *self->signal_dbm = *signal_dbm;
  }
  else {
    self->signal_dbm = nullptr;
  }
  if (frequency_mhz != nullptr) {
    self->frequency_mhz = static_cast<int64_t*>(malloc(sizeof(int64_t)));
    *self->frequency_mhz = *frequency_mhz;
  }
  else {
    self->frequency_mhz = nullptr;
  }
  self->security = security;
  self->is_hidden = is_hidden;
  return self;
}

const gchar* layrz_wifi_wifi_network_get_ssid(LayrzWifiWifiNetwork* self) {
  g_return_val_if_fail(LAYRZ_WIFI_IS_WIFI_NETWORK(self), nullptr);
  return self->ssid;
}

const gchar* layrz_wifi_wifi_network_get_bssid(LayrzWifiWifiNetwork* self) {
  g_return_val_if_fail(LAYRZ_WIFI_IS_WIFI_NETWORK(self), nullptr);
  return self->bssid;
}

int64_t* layrz_wifi_wifi_network_get_signal_dbm(LayrzWifiWifiNetwork* self) {
  g_return_val_if_fail(LAYRZ_WIFI_IS_WIFI_NETWORK(self), nullptr);
  return self->signal_dbm;
}

int64_t* layrz_wifi_wifi_network_get_frequency_mhz(LayrzWifiWifiNetwork* self) {
  g_return_val_if_fail(LAYRZ_WIFI_IS_WIFI_NETWORK(self), nullptr);
  return self->frequency_mhz;
}

LayrzWifiWifiSecurity layrz_wifi_wifi_network_get_security(LayrzWifiWifiNetwork* self) {
  g_return_val_if_fail(LAYRZ_WIFI_IS_WIFI_NETWORK(self), static_cast<LayrzWifiWifiSecurity>(0));
  return self->security;
}

gboolean layrz_wifi_wifi_network_get_is_hidden(LayrzWifiWifiNetwork* self) {
  g_return_val_if_fail(LAYRZ_WIFI_IS_WIFI_NETWORK(self), FALSE);
  return self->is_hidden;
}

static FlValue* layrz_wifi_wifi_network_to_list(LayrzWifiWifiNetwork* self) {
  FlValue* values = fl_value_new_list();
  fl_value_append_take(values, fl_value_new_string(self->ssid));
  fl_value_append_take(values, self->bssid != nullptr ? fl_value_new_string(self->bssid) : fl_value_new_null());
  fl_value_append_take(values, self->signal_dbm != nullptr ? fl_value_new_int(*self->signal_dbm) : fl_value_new_null());
  fl_value_append_take(values, self->frequency_mhz != nullptr ? fl_value_new_int(*self->frequency_mhz) : fl_value_new_null());
  fl_value_append_take(values, fl_value_new_custom(129, fl_value_new_int(self->security), (GDestroyNotify)fl_value_unref));
  fl_value_append_take(values, fl_value_new_bool(self->is_hidden));
  return values;
}

static LayrzWifiWifiNetwork* layrz_wifi_wifi_network_new_from_list(FlValue* values) {
  FlValue* value0 = fl_value_get_list_value(values, 0);
  const gchar* ssid = fl_value_get_string(value0);
  FlValue* value1 = fl_value_get_list_value(values, 1);
  const gchar* bssid = nullptr;
  if (fl_value_get_type(value1) != FL_VALUE_TYPE_NULL) {
    bssid = fl_value_get_string(value1);
  }
  FlValue* value2 = fl_value_get_list_value(values, 2);
  int64_t* signal_dbm = nullptr;
  int64_t signal_dbm_value;
  if (fl_value_get_type(value2) != FL_VALUE_TYPE_NULL) {
    signal_dbm_value = fl_value_get_int(value2);
    signal_dbm = &signal_dbm_value;
  }
  FlValue* value3 = fl_value_get_list_value(values, 3);
  int64_t* frequency_mhz = nullptr;
  int64_t frequency_mhz_value;
  if (fl_value_get_type(value3) != FL_VALUE_TYPE_NULL) {
    frequency_mhz_value = fl_value_get_int(value3);
    frequency_mhz = &frequency_mhz_value;
  }
  FlValue* value4 = fl_value_get_list_value(values, 4);
  LayrzWifiWifiSecurity security = static_cast<LayrzWifiWifiSecurity>(fl_value_get_int(reinterpret_cast<FlValue*>(const_cast<gpointer>(fl_value_get_custom_value(value4)))));
  FlValue* value5 = fl_value_get_list_value(values, 5);
  gboolean is_hidden = fl_value_get_bool(value5);
  return layrz_wifi_wifi_network_new(ssid, bssid, signal_dbm, frequency_mhz, security, is_hidden);
}

struct _LayrzWifiMessageCodec {
  FlStandardMessageCodec parent_instance;

};

G_DEFINE_TYPE(LayrzWifiMessageCodec, layrz_wifi_message_codec, fl_standard_message_codec_get_type())

static gboolean layrz_wifi_message_codec_write_layrz_wifi_wifi_security(FlStandardMessageCodec* codec, GByteArray* buffer, FlValue* value, GError** error) {
  uint8_t type = 129;
  g_byte_array_append(buffer, &type, sizeof(uint8_t));
  return fl_standard_message_codec_write_value(codec, buffer, value, error);
}

static gboolean layrz_wifi_message_codec_write_layrz_wifi_wifi_permission_status(FlStandardMessageCodec* codec, GByteArray* buffer, FlValue* value, GError** error) {
  uint8_t type = 130;
  g_byte_array_append(buffer, &type, sizeof(uint8_t));
  return fl_standard_message_codec_write_value(codec, buffer, value, error);
}

static gboolean layrz_wifi_message_codec_write_layrz_wifi_wifi_network(FlStandardMessageCodec* codec, GByteArray* buffer, LayrzWifiWifiNetwork* value, GError** error) {
  uint8_t type = 131;
  g_byte_array_append(buffer, &type, sizeof(uint8_t));
  g_autoptr(FlValue) values = layrz_wifi_wifi_network_to_list(value);
  return fl_standard_message_codec_write_value(codec, buffer, values, error);
}

static gboolean layrz_wifi_message_codec_write_value(FlStandardMessageCodec* codec, GByteArray* buffer, FlValue* value, GError** error) {
  if (fl_value_get_type(value) == FL_VALUE_TYPE_CUSTOM) {
    switch (fl_value_get_custom_type(value)) {
      case 129:
        return layrz_wifi_message_codec_write_layrz_wifi_wifi_security(codec, buffer, reinterpret_cast<FlValue*>(const_cast<gpointer>(fl_value_get_custom_value(value))), error);
      case 130:
        return layrz_wifi_message_codec_write_layrz_wifi_wifi_permission_status(codec, buffer, reinterpret_cast<FlValue*>(const_cast<gpointer>(fl_value_get_custom_value(value))), error);
      case 131:
        return layrz_wifi_message_codec_write_layrz_wifi_wifi_network(codec, buffer, LAYRZ_WIFI_WIFI_NETWORK(fl_value_get_custom_value_object(value)), error);
    }
  }

  return FL_STANDARD_MESSAGE_CODEC_CLASS(layrz_wifi_message_codec_parent_class)->write_value(codec, buffer, value, error);
}

static FlValue* layrz_wifi_message_codec_read_layrz_wifi_wifi_security(FlStandardMessageCodec* codec, GBytes* buffer, size_t* offset, GError** error) {
  return fl_value_new_custom(129, fl_standard_message_codec_read_value(codec, buffer, offset, error), (GDestroyNotify)fl_value_unref);
}

static FlValue* layrz_wifi_message_codec_read_layrz_wifi_wifi_permission_status(FlStandardMessageCodec* codec, GBytes* buffer, size_t* offset, GError** error) {
  return fl_value_new_custom(130, fl_standard_message_codec_read_value(codec, buffer, offset, error), (GDestroyNotify)fl_value_unref);
}

static FlValue* layrz_wifi_message_codec_read_layrz_wifi_wifi_network(FlStandardMessageCodec* codec, GBytes* buffer, size_t* offset, GError** error) {
  g_autoptr(FlValue) values = fl_standard_message_codec_read_value(codec, buffer, offset, error);
  if (values == nullptr) {
    return nullptr;
  }

  g_autoptr(LayrzWifiWifiNetwork) value = layrz_wifi_wifi_network_new_from_list(values);
  if (value == nullptr) {
    g_set_error(error, FL_MESSAGE_CODEC_ERROR, FL_MESSAGE_CODEC_ERROR_FAILED, "Invalid data received for MessageData");
    return nullptr;
  }

  return fl_value_new_custom_object(131, G_OBJECT(value));
}

static FlValue* layrz_wifi_message_codec_read_value_of_type(FlStandardMessageCodec* codec, GBytes* buffer, size_t* offset, int type, GError** error) {
  switch (type) {
    case 129:
      return layrz_wifi_message_codec_read_layrz_wifi_wifi_security(codec, buffer, offset, error);
    case 130:
      return layrz_wifi_message_codec_read_layrz_wifi_wifi_permission_status(codec, buffer, offset, error);
    case 131:
      return layrz_wifi_message_codec_read_layrz_wifi_wifi_network(codec, buffer, offset, error);
    default:
      return FL_STANDARD_MESSAGE_CODEC_CLASS(layrz_wifi_message_codec_parent_class)->read_value_of_type(codec, buffer, offset, type, error);
  }
}

static void layrz_wifi_message_codec_init(LayrzWifiMessageCodec* self) {
}

static void layrz_wifi_message_codec_class_init(LayrzWifiMessageCodecClass* klass) {
  FL_STANDARD_MESSAGE_CODEC_CLASS(klass)->write_value = layrz_wifi_message_codec_write_value;
  FL_STANDARD_MESSAGE_CODEC_CLASS(klass)->read_value_of_type = layrz_wifi_message_codec_read_value_of_type;
}

static LayrzWifiMessageCodec* layrz_wifi_message_codec_new() {
  LayrzWifiMessageCodec* self = LAYRZ_WIFI_MESSAGE_CODEC(g_object_new(layrz_wifi_message_codec_get_type(), nullptr));
  return self;
}

struct _LayrzWifiLayrzWifiApiHasDiscoveryResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(LayrzWifiLayrzWifiApiHasDiscoveryResponse, layrz_wifi_layrz_wifi_api_has_discovery_response, G_TYPE_OBJECT)

static void layrz_wifi_layrz_wifi_api_has_discovery_response_dispose(GObject* object) {
  LayrzWifiLayrzWifiApiHasDiscoveryResponse* self = LAYRZ_WIFI_LAYRZ_WIFI_API_HAS_DISCOVERY_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(layrz_wifi_layrz_wifi_api_has_discovery_response_parent_class)->dispose(object);
}

static void layrz_wifi_layrz_wifi_api_has_discovery_response_init(LayrzWifiLayrzWifiApiHasDiscoveryResponse* self) {
}

static void layrz_wifi_layrz_wifi_api_has_discovery_response_class_init(LayrzWifiLayrzWifiApiHasDiscoveryResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = layrz_wifi_layrz_wifi_api_has_discovery_response_dispose;
}

LayrzWifiLayrzWifiApiHasDiscoveryResponse* layrz_wifi_layrz_wifi_api_has_discovery_response_new(gboolean return_value) {
  LayrzWifiLayrzWifiApiHasDiscoveryResponse* self = LAYRZ_WIFI_LAYRZ_WIFI_API_HAS_DISCOVERY_RESPONSE(g_object_new(layrz_wifi_layrz_wifi_api_has_discovery_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_bool(return_value));
  return self;
}

LayrzWifiLayrzWifiApiHasDiscoveryResponse* layrz_wifi_layrz_wifi_api_has_discovery_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  LayrzWifiLayrzWifiApiHasDiscoveryResponse* self = LAYRZ_WIFI_LAYRZ_WIFI_API_HAS_DISCOVERY_RESPONSE(g_object_new(layrz_wifi_layrz_wifi_api_has_discovery_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

struct _LayrzWifiLayrzWifiApiHasCurrentSsidResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(LayrzWifiLayrzWifiApiHasCurrentSsidResponse, layrz_wifi_layrz_wifi_api_has_current_ssid_response, G_TYPE_OBJECT)

static void layrz_wifi_layrz_wifi_api_has_current_ssid_response_dispose(GObject* object) {
  LayrzWifiLayrzWifiApiHasCurrentSsidResponse* self = LAYRZ_WIFI_LAYRZ_WIFI_API_HAS_CURRENT_SSID_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(layrz_wifi_layrz_wifi_api_has_current_ssid_response_parent_class)->dispose(object);
}

static void layrz_wifi_layrz_wifi_api_has_current_ssid_response_init(LayrzWifiLayrzWifiApiHasCurrentSsidResponse* self) {
}

static void layrz_wifi_layrz_wifi_api_has_current_ssid_response_class_init(LayrzWifiLayrzWifiApiHasCurrentSsidResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = layrz_wifi_layrz_wifi_api_has_current_ssid_response_dispose;
}

LayrzWifiLayrzWifiApiHasCurrentSsidResponse* layrz_wifi_layrz_wifi_api_has_current_ssid_response_new(gboolean return_value) {
  LayrzWifiLayrzWifiApiHasCurrentSsidResponse* self = LAYRZ_WIFI_LAYRZ_WIFI_API_HAS_CURRENT_SSID_RESPONSE(g_object_new(layrz_wifi_layrz_wifi_api_has_current_ssid_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_bool(return_value));
  return self;
}

LayrzWifiLayrzWifiApiHasCurrentSsidResponse* layrz_wifi_layrz_wifi_api_has_current_ssid_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  LayrzWifiLayrzWifiApiHasCurrentSsidResponse* self = LAYRZ_WIFI_LAYRZ_WIFI_API_HAS_CURRENT_SSID_RESPONSE(g_object_new(layrz_wifi_layrz_wifi_api_has_current_ssid_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

struct _LayrzWifiLayrzWifiApiCurrentSsidResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(LayrzWifiLayrzWifiApiCurrentSsidResponse, layrz_wifi_layrz_wifi_api_current_ssid_response, G_TYPE_OBJECT)

static void layrz_wifi_layrz_wifi_api_current_ssid_response_dispose(GObject* object) {
  LayrzWifiLayrzWifiApiCurrentSsidResponse* self = LAYRZ_WIFI_LAYRZ_WIFI_API_CURRENT_SSID_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(layrz_wifi_layrz_wifi_api_current_ssid_response_parent_class)->dispose(object);
}

static void layrz_wifi_layrz_wifi_api_current_ssid_response_init(LayrzWifiLayrzWifiApiCurrentSsidResponse* self) {
}

static void layrz_wifi_layrz_wifi_api_current_ssid_response_class_init(LayrzWifiLayrzWifiApiCurrentSsidResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = layrz_wifi_layrz_wifi_api_current_ssid_response_dispose;
}

LayrzWifiLayrzWifiApiCurrentSsidResponse* layrz_wifi_layrz_wifi_api_current_ssid_response_new(const gchar* return_value) {
  LayrzWifiLayrzWifiApiCurrentSsidResponse* self = LAYRZ_WIFI_LAYRZ_WIFI_API_CURRENT_SSID_RESPONSE(g_object_new(layrz_wifi_layrz_wifi_api_current_ssid_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, return_value != nullptr ? fl_value_new_string(return_value) : fl_value_new_null());
  return self;
}

LayrzWifiLayrzWifiApiCurrentSsidResponse* layrz_wifi_layrz_wifi_api_current_ssid_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  LayrzWifiLayrzWifiApiCurrentSsidResponse* self = LAYRZ_WIFI_LAYRZ_WIFI_API_CURRENT_SSID_RESPONSE(g_object_new(layrz_wifi_layrz_wifi_api_current_ssid_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

struct _LayrzWifiLayrzWifiApiStartScanResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(LayrzWifiLayrzWifiApiStartScanResponse, layrz_wifi_layrz_wifi_api_start_scan_response, G_TYPE_OBJECT)

static void layrz_wifi_layrz_wifi_api_start_scan_response_dispose(GObject* object) {
  LayrzWifiLayrzWifiApiStartScanResponse* self = LAYRZ_WIFI_LAYRZ_WIFI_API_START_SCAN_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(layrz_wifi_layrz_wifi_api_start_scan_response_parent_class)->dispose(object);
}

static void layrz_wifi_layrz_wifi_api_start_scan_response_init(LayrzWifiLayrzWifiApiStartScanResponse* self) {
}

static void layrz_wifi_layrz_wifi_api_start_scan_response_class_init(LayrzWifiLayrzWifiApiStartScanResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = layrz_wifi_layrz_wifi_api_start_scan_response_dispose;
}

LayrzWifiLayrzWifiApiStartScanResponse* layrz_wifi_layrz_wifi_api_start_scan_response_new() {
  LayrzWifiLayrzWifiApiStartScanResponse* self = LAYRZ_WIFI_LAYRZ_WIFI_API_START_SCAN_RESPONSE(g_object_new(layrz_wifi_layrz_wifi_api_start_scan_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_null());
  return self;
}

LayrzWifiLayrzWifiApiStartScanResponse* layrz_wifi_layrz_wifi_api_start_scan_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  LayrzWifiLayrzWifiApiStartScanResponse* self = LAYRZ_WIFI_LAYRZ_WIFI_API_START_SCAN_RESPONSE(g_object_new(layrz_wifi_layrz_wifi_api_start_scan_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

struct _LayrzWifiLayrzWifiApiStopScanResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(LayrzWifiLayrzWifiApiStopScanResponse, layrz_wifi_layrz_wifi_api_stop_scan_response, G_TYPE_OBJECT)

static void layrz_wifi_layrz_wifi_api_stop_scan_response_dispose(GObject* object) {
  LayrzWifiLayrzWifiApiStopScanResponse* self = LAYRZ_WIFI_LAYRZ_WIFI_API_STOP_SCAN_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(layrz_wifi_layrz_wifi_api_stop_scan_response_parent_class)->dispose(object);
}

static void layrz_wifi_layrz_wifi_api_stop_scan_response_init(LayrzWifiLayrzWifiApiStopScanResponse* self) {
}

static void layrz_wifi_layrz_wifi_api_stop_scan_response_class_init(LayrzWifiLayrzWifiApiStopScanResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = layrz_wifi_layrz_wifi_api_stop_scan_response_dispose;
}

LayrzWifiLayrzWifiApiStopScanResponse* layrz_wifi_layrz_wifi_api_stop_scan_response_new() {
  LayrzWifiLayrzWifiApiStopScanResponse* self = LAYRZ_WIFI_LAYRZ_WIFI_API_STOP_SCAN_RESPONSE(g_object_new(layrz_wifi_layrz_wifi_api_stop_scan_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_null());
  return self;
}

LayrzWifiLayrzWifiApiStopScanResponse* layrz_wifi_layrz_wifi_api_stop_scan_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  LayrzWifiLayrzWifiApiStopScanResponse* self = LAYRZ_WIFI_LAYRZ_WIFI_API_STOP_SCAN_RESPONSE(g_object_new(layrz_wifi_layrz_wifi_api_stop_scan_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

struct _LayrzWifiLayrzWifiApiRequestPermissionsResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(LayrzWifiLayrzWifiApiRequestPermissionsResponse, layrz_wifi_layrz_wifi_api_request_permissions_response, G_TYPE_OBJECT)

static void layrz_wifi_layrz_wifi_api_request_permissions_response_dispose(GObject* object) {
  LayrzWifiLayrzWifiApiRequestPermissionsResponse* self = LAYRZ_WIFI_LAYRZ_WIFI_API_REQUEST_PERMISSIONS_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(layrz_wifi_layrz_wifi_api_request_permissions_response_parent_class)->dispose(object);
}

static void layrz_wifi_layrz_wifi_api_request_permissions_response_init(LayrzWifiLayrzWifiApiRequestPermissionsResponse* self) {
}

static void layrz_wifi_layrz_wifi_api_request_permissions_response_class_init(LayrzWifiLayrzWifiApiRequestPermissionsResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = layrz_wifi_layrz_wifi_api_request_permissions_response_dispose;
}

LayrzWifiLayrzWifiApiRequestPermissionsResponse* layrz_wifi_layrz_wifi_api_request_permissions_response_new(gboolean return_value) {
  LayrzWifiLayrzWifiApiRequestPermissionsResponse* self = LAYRZ_WIFI_LAYRZ_WIFI_API_REQUEST_PERMISSIONS_RESPONSE(g_object_new(layrz_wifi_layrz_wifi_api_request_permissions_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_bool(return_value));
  return self;
}

LayrzWifiLayrzWifiApiRequestPermissionsResponse* layrz_wifi_layrz_wifi_api_request_permissions_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  LayrzWifiLayrzWifiApiRequestPermissionsResponse* self = LAYRZ_WIFI_LAYRZ_WIFI_API_REQUEST_PERMISSIONS_RESPONSE(g_object_new(layrz_wifi_layrz_wifi_api_request_permissions_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

struct _LayrzWifiLayrzWifiApiPermissionStatusResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(LayrzWifiLayrzWifiApiPermissionStatusResponse, layrz_wifi_layrz_wifi_api_permission_status_response, G_TYPE_OBJECT)

static void layrz_wifi_layrz_wifi_api_permission_status_response_dispose(GObject* object) {
  LayrzWifiLayrzWifiApiPermissionStatusResponse* self = LAYRZ_WIFI_LAYRZ_WIFI_API_PERMISSION_STATUS_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(layrz_wifi_layrz_wifi_api_permission_status_response_parent_class)->dispose(object);
}

static void layrz_wifi_layrz_wifi_api_permission_status_response_init(LayrzWifiLayrzWifiApiPermissionStatusResponse* self) {
}

static void layrz_wifi_layrz_wifi_api_permission_status_response_class_init(LayrzWifiLayrzWifiApiPermissionStatusResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = layrz_wifi_layrz_wifi_api_permission_status_response_dispose;
}

LayrzWifiLayrzWifiApiPermissionStatusResponse* layrz_wifi_layrz_wifi_api_permission_status_response_new(LayrzWifiWifiPermissionStatus return_value) {
  LayrzWifiLayrzWifiApiPermissionStatusResponse* self = LAYRZ_WIFI_LAYRZ_WIFI_API_PERMISSION_STATUS_RESPONSE(g_object_new(layrz_wifi_layrz_wifi_api_permission_status_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_custom(130, fl_value_new_int(return_value), (GDestroyNotify)fl_value_unref));
  return self;
}

LayrzWifiLayrzWifiApiPermissionStatusResponse* layrz_wifi_layrz_wifi_api_permission_status_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  LayrzWifiLayrzWifiApiPermissionStatusResponse* self = LAYRZ_WIFI_LAYRZ_WIFI_API_PERMISSION_STATUS_RESPONSE(g_object_new(layrz_wifi_layrz_wifi_api_permission_status_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

struct _LayrzWifiLayrzWifiApi {
  GObject parent_instance;

  const LayrzWifiLayrzWifiApiVTable* vtable;
  gpointer user_data;
  GDestroyNotify user_data_free_func;
};

G_DEFINE_TYPE(LayrzWifiLayrzWifiApi, layrz_wifi_layrz_wifi_api, G_TYPE_OBJECT)

static void layrz_wifi_layrz_wifi_api_dispose(GObject* object) {
  LayrzWifiLayrzWifiApi* self = LAYRZ_WIFI_LAYRZ_WIFI_API(object);
  if (self->user_data != nullptr) {
    self->user_data_free_func(self->user_data);
  }
  self->user_data = nullptr;
  G_OBJECT_CLASS(layrz_wifi_layrz_wifi_api_parent_class)->dispose(object);
}

static void layrz_wifi_layrz_wifi_api_init(LayrzWifiLayrzWifiApi* self) {
}

static void layrz_wifi_layrz_wifi_api_class_init(LayrzWifiLayrzWifiApiClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = layrz_wifi_layrz_wifi_api_dispose;
}

static LayrzWifiLayrzWifiApi* layrz_wifi_layrz_wifi_api_new(const LayrzWifiLayrzWifiApiVTable* vtable, gpointer user_data, GDestroyNotify user_data_free_func) {
  LayrzWifiLayrzWifiApi* self = LAYRZ_WIFI_LAYRZ_WIFI_API(g_object_new(layrz_wifi_layrz_wifi_api_get_type(), nullptr));
  self->vtable = vtable;
  self->user_data = user_data;
  self->user_data_free_func = user_data_free_func;
  return self;
}

static void layrz_wifi_layrz_wifi_api_has_discovery_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  LayrzWifiLayrzWifiApi* self = LAYRZ_WIFI_LAYRZ_WIFI_API(user_data);

  if (self->vtable == nullptr || self->vtable->has_discovery == nullptr) {
    return;
  }

  g_autoptr(LayrzWifiLayrzWifiApiHasDiscoveryResponse) response = self->vtable->has_discovery(self->user_data);
  if (response == nullptr) {
    g_warning("No response returned to %s.%s", "LayrzWifiApi", "hasDiscovery");
    return;
  }

  g_autoptr(GError) error = NULL;
  if (!fl_basic_message_channel_respond(channel, response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "LayrzWifiApi", "hasDiscovery", error->message);
  }
}

static void layrz_wifi_layrz_wifi_api_has_current_ssid_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  LayrzWifiLayrzWifiApi* self = LAYRZ_WIFI_LAYRZ_WIFI_API(user_data);

  if (self->vtable == nullptr || self->vtable->has_current_ssid == nullptr) {
    return;
  }

  g_autoptr(LayrzWifiLayrzWifiApiHasCurrentSsidResponse) response = self->vtable->has_current_ssid(self->user_data);
  if (response == nullptr) {
    g_warning("No response returned to %s.%s", "LayrzWifiApi", "hasCurrentSsid");
    return;
  }

  g_autoptr(GError) error = NULL;
  if (!fl_basic_message_channel_respond(channel, response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "LayrzWifiApi", "hasCurrentSsid", error->message);
  }
}

static void layrz_wifi_layrz_wifi_api_current_ssid_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  LayrzWifiLayrzWifiApi* self = LAYRZ_WIFI_LAYRZ_WIFI_API(user_data);

  if (self->vtable == nullptr || self->vtable->current_ssid == nullptr) {
    return;
  }

  g_autoptr(LayrzWifiLayrzWifiApiCurrentSsidResponse) response = self->vtable->current_ssid(self->user_data);
  if (response == nullptr) {
    g_warning("No response returned to %s.%s", "LayrzWifiApi", "currentSsid");
    return;
  }

  g_autoptr(GError) error = NULL;
  if (!fl_basic_message_channel_respond(channel, response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "LayrzWifiApi", "currentSsid", error->message);
  }
}

static void layrz_wifi_layrz_wifi_api_start_scan_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  LayrzWifiLayrzWifiApi* self = LAYRZ_WIFI_LAYRZ_WIFI_API(user_data);

  if (self->vtable == nullptr || self->vtable->start_scan == nullptr) {
    return;
  }

  g_autoptr(LayrzWifiLayrzWifiApiStartScanResponse) response = self->vtable->start_scan(self->user_data);
  if (response == nullptr) {
    g_warning("No response returned to %s.%s", "LayrzWifiApi", "startScan");
    return;
  }

  g_autoptr(GError) error = NULL;
  if (!fl_basic_message_channel_respond(channel, response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "LayrzWifiApi", "startScan", error->message);
  }
}

static void layrz_wifi_layrz_wifi_api_stop_scan_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  LayrzWifiLayrzWifiApi* self = LAYRZ_WIFI_LAYRZ_WIFI_API(user_data);

  if (self->vtable == nullptr || self->vtable->stop_scan == nullptr) {
    return;
  }

  g_autoptr(LayrzWifiLayrzWifiApiStopScanResponse) response = self->vtable->stop_scan(self->user_data);
  if (response == nullptr) {
    g_warning("No response returned to %s.%s", "LayrzWifiApi", "stopScan");
    return;
  }

  g_autoptr(GError) error = NULL;
  if (!fl_basic_message_channel_respond(channel, response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "LayrzWifiApi", "stopScan", error->message);
  }
}

static void layrz_wifi_layrz_wifi_api_request_permissions_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  LayrzWifiLayrzWifiApi* self = LAYRZ_WIFI_LAYRZ_WIFI_API(user_data);

  if (self->vtable == nullptr || self->vtable->request_permissions == nullptr) {
    return;
  }

  g_autoptr(LayrzWifiLayrzWifiApiRequestPermissionsResponse) response = self->vtable->request_permissions(self->user_data);
  if (response == nullptr) {
    g_warning("No response returned to %s.%s", "LayrzWifiApi", "requestPermissions");
    return;
  }

  g_autoptr(GError) error = NULL;
  if (!fl_basic_message_channel_respond(channel, response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "LayrzWifiApi", "requestPermissions", error->message);
  }
}

static void layrz_wifi_layrz_wifi_api_permission_status_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  LayrzWifiLayrzWifiApi* self = LAYRZ_WIFI_LAYRZ_WIFI_API(user_data);

  if (self->vtable == nullptr || self->vtable->permission_status == nullptr) {
    return;
  }

  g_autoptr(LayrzWifiLayrzWifiApiPermissionStatusResponse) response = self->vtable->permission_status(self->user_data);
  if (response == nullptr) {
    g_warning("No response returned to %s.%s", "LayrzWifiApi", "permissionStatus");
    return;
  }

  g_autoptr(GError) error = NULL;
  if (!fl_basic_message_channel_respond(channel, response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "LayrzWifiApi", "permissionStatus", error->message);
  }
}

void layrz_wifi_layrz_wifi_api_set_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix, const LayrzWifiLayrzWifiApiVTable* vtable, gpointer user_data, GDestroyNotify user_data_free_func) {
  g_autofree gchar* dot_suffix = suffix != nullptr ? g_strdup_printf(".%s", suffix) : g_strdup("");
  g_autoptr(LayrzWifiLayrzWifiApi) api_data = layrz_wifi_layrz_wifi_api_new(vtable, user_data, user_data_free_func);

  g_autoptr(LayrzWifiMessageCodec) codec = layrz_wifi_message_codec_new();
  g_autofree gchar* has_discovery_channel_name = g_strdup_printf("dev.flutter.pigeon.layrz_wifi.LayrzWifiApi.hasDiscovery%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) has_discovery_channel = fl_basic_message_channel_new(messenger, has_discovery_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(has_discovery_channel, layrz_wifi_layrz_wifi_api_has_discovery_cb, g_object_ref(api_data), g_object_unref);
  g_autofree gchar* has_current_ssid_channel_name = g_strdup_printf("dev.flutter.pigeon.layrz_wifi.LayrzWifiApi.hasCurrentSsid%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) has_current_ssid_channel = fl_basic_message_channel_new(messenger, has_current_ssid_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(has_current_ssid_channel, layrz_wifi_layrz_wifi_api_has_current_ssid_cb, g_object_ref(api_data), g_object_unref);
  g_autofree gchar* current_ssid_channel_name = g_strdup_printf("dev.flutter.pigeon.layrz_wifi.LayrzWifiApi.currentSsid%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) current_ssid_channel = fl_basic_message_channel_new(messenger, current_ssid_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(current_ssid_channel, layrz_wifi_layrz_wifi_api_current_ssid_cb, g_object_ref(api_data), g_object_unref);
  g_autofree gchar* start_scan_channel_name = g_strdup_printf("dev.flutter.pigeon.layrz_wifi.LayrzWifiApi.startScan%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) start_scan_channel = fl_basic_message_channel_new(messenger, start_scan_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(start_scan_channel, layrz_wifi_layrz_wifi_api_start_scan_cb, g_object_ref(api_data), g_object_unref);
  g_autofree gchar* stop_scan_channel_name = g_strdup_printf("dev.flutter.pigeon.layrz_wifi.LayrzWifiApi.stopScan%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) stop_scan_channel = fl_basic_message_channel_new(messenger, stop_scan_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(stop_scan_channel, layrz_wifi_layrz_wifi_api_stop_scan_cb, g_object_ref(api_data), g_object_unref);
  g_autofree gchar* request_permissions_channel_name = g_strdup_printf("dev.flutter.pigeon.layrz_wifi.LayrzWifiApi.requestPermissions%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) request_permissions_channel = fl_basic_message_channel_new(messenger, request_permissions_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(request_permissions_channel, layrz_wifi_layrz_wifi_api_request_permissions_cb, g_object_ref(api_data), g_object_unref);
  g_autofree gchar* permission_status_channel_name = g_strdup_printf("dev.flutter.pigeon.layrz_wifi.LayrzWifiApi.permissionStatus%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) permission_status_channel = fl_basic_message_channel_new(messenger, permission_status_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(permission_status_channel, layrz_wifi_layrz_wifi_api_permission_status_cb, g_object_ref(api_data), g_object_unref);
}

void layrz_wifi_layrz_wifi_api_clear_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix) {
  g_autofree gchar* dot_suffix = suffix != nullptr ? g_strdup_printf(".%s", suffix) : g_strdup("");

  g_autoptr(LayrzWifiMessageCodec) codec = layrz_wifi_message_codec_new();
  g_autofree gchar* has_discovery_channel_name = g_strdup_printf("dev.flutter.pigeon.layrz_wifi.LayrzWifiApi.hasDiscovery%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) has_discovery_channel = fl_basic_message_channel_new(messenger, has_discovery_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(has_discovery_channel, nullptr, nullptr, nullptr);
  g_autofree gchar* has_current_ssid_channel_name = g_strdup_printf("dev.flutter.pigeon.layrz_wifi.LayrzWifiApi.hasCurrentSsid%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) has_current_ssid_channel = fl_basic_message_channel_new(messenger, has_current_ssid_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(has_current_ssid_channel, nullptr, nullptr, nullptr);
  g_autofree gchar* current_ssid_channel_name = g_strdup_printf("dev.flutter.pigeon.layrz_wifi.LayrzWifiApi.currentSsid%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) current_ssid_channel = fl_basic_message_channel_new(messenger, current_ssid_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(current_ssid_channel, nullptr, nullptr, nullptr);
  g_autofree gchar* start_scan_channel_name = g_strdup_printf("dev.flutter.pigeon.layrz_wifi.LayrzWifiApi.startScan%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) start_scan_channel = fl_basic_message_channel_new(messenger, start_scan_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(start_scan_channel, nullptr, nullptr, nullptr);
  g_autofree gchar* stop_scan_channel_name = g_strdup_printf("dev.flutter.pigeon.layrz_wifi.LayrzWifiApi.stopScan%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) stop_scan_channel = fl_basic_message_channel_new(messenger, stop_scan_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(stop_scan_channel, nullptr, nullptr, nullptr);
  g_autofree gchar* request_permissions_channel_name = g_strdup_printf("dev.flutter.pigeon.layrz_wifi.LayrzWifiApi.requestPermissions%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) request_permissions_channel = fl_basic_message_channel_new(messenger, request_permissions_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(request_permissions_channel, nullptr, nullptr, nullptr);
  g_autofree gchar* permission_status_channel_name = g_strdup_printf("dev.flutter.pigeon.layrz_wifi.LayrzWifiApi.permissionStatus%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) permission_status_channel = fl_basic_message_channel_new(messenger, permission_status_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(permission_status_channel, nullptr, nullptr, nullptr);
}

struct _LayrzWifiLayrzWifiEvents {
  GObject parent_instance;

  FlBinaryMessenger* messenger;
  gchar *suffix;
};

G_DEFINE_TYPE(LayrzWifiLayrzWifiEvents, layrz_wifi_layrz_wifi_events, G_TYPE_OBJECT)

static void layrz_wifi_layrz_wifi_events_dispose(GObject* object) {
  LayrzWifiLayrzWifiEvents* self = LAYRZ_WIFI_LAYRZ_WIFI_EVENTS(object);
  g_clear_object(&self->messenger);
  g_clear_pointer(&self->suffix, g_free);
  G_OBJECT_CLASS(layrz_wifi_layrz_wifi_events_parent_class)->dispose(object);
}

static void layrz_wifi_layrz_wifi_events_init(LayrzWifiLayrzWifiEvents* self) {
}

static void layrz_wifi_layrz_wifi_events_class_init(LayrzWifiLayrzWifiEventsClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = layrz_wifi_layrz_wifi_events_dispose;
}

LayrzWifiLayrzWifiEvents* layrz_wifi_layrz_wifi_events_new(FlBinaryMessenger* messenger, const gchar* suffix) {
  LayrzWifiLayrzWifiEvents* self = LAYRZ_WIFI_LAYRZ_WIFI_EVENTS(g_object_new(layrz_wifi_layrz_wifi_events_get_type(), nullptr));
  self->messenger = FL_BINARY_MESSENGER(g_object_ref(messenger));
  self->suffix = suffix != nullptr ? g_strdup_printf(".%s", suffix) : g_strdup("");
  return self;
}

struct _LayrzWifiLayrzWifiEventsOnScanResultResponse {
  GObject parent_instance;

  FlValue* error;
};

G_DEFINE_TYPE(LayrzWifiLayrzWifiEventsOnScanResultResponse, layrz_wifi_layrz_wifi_events_on_scan_result_response, G_TYPE_OBJECT)

static void layrz_wifi_layrz_wifi_events_on_scan_result_response_dispose(GObject* object) {
  LayrzWifiLayrzWifiEventsOnScanResultResponse* self = LAYRZ_WIFI_LAYRZ_WIFI_EVENTS_ON_SCAN_RESULT_RESPONSE(object);
  g_clear_pointer(&self->error, fl_value_unref);
  G_OBJECT_CLASS(layrz_wifi_layrz_wifi_events_on_scan_result_response_parent_class)->dispose(object);
}

static void layrz_wifi_layrz_wifi_events_on_scan_result_response_init(LayrzWifiLayrzWifiEventsOnScanResultResponse* self) {
}

static void layrz_wifi_layrz_wifi_events_on_scan_result_response_class_init(LayrzWifiLayrzWifiEventsOnScanResultResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = layrz_wifi_layrz_wifi_events_on_scan_result_response_dispose;
}

static LayrzWifiLayrzWifiEventsOnScanResultResponse* layrz_wifi_layrz_wifi_events_on_scan_result_response_new(FlValue* response) {
  LayrzWifiLayrzWifiEventsOnScanResultResponse* self = LAYRZ_WIFI_LAYRZ_WIFI_EVENTS_ON_SCAN_RESULT_RESPONSE(g_object_new(layrz_wifi_layrz_wifi_events_on_scan_result_response_get_type(), nullptr));
  if (fl_value_get_length(response) > 1) {
    self->error = fl_value_ref(response);
  }
  return self;
}

gboolean layrz_wifi_layrz_wifi_events_on_scan_result_response_is_error(LayrzWifiLayrzWifiEventsOnScanResultResponse* self) {
  g_return_val_if_fail(LAYRZ_WIFI_IS_LAYRZ_WIFI_EVENTS_ON_SCAN_RESULT_RESPONSE(self), FALSE);
  return self->error != nullptr;
}

const gchar* layrz_wifi_layrz_wifi_events_on_scan_result_response_get_error_code(LayrzWifiLayrzWifiEventsOnScanResultResponse* self) {
  g_return_val_if_fail(LAYRZ_WIFI_IS_LAYRZ_WIFI_EVENTS_ON_SCAN_RESULT_RESPONSE(self), nullptr);
  g_assert(layrz_wifi_layrz_wifi_events_on_scan_result_response_is_error(self));
  return fl_value_get_string(fl_value_get_list_value(self->error, 0));
}

const gchar* layrz_wifi_layrz_wifi_events_on_scan_result_response_get_error_message(LayrzWifiLayrzWifiEventsOnScanResultResponse* self) {
  g_return_val_if_fail(LAYRZ_WIFI_IS_LAYRZ_WIFI_EVENTS_ON_SCAN_RESULT_RESPONSE(self), nullptr);
  g_assert(layrz_wifi_layrz_wifi_events_on_scan_result_response_is_error(self));
  return fl_value_get_string(fl_value_get_list_value(self->error, 1));
}

FlValue* layrz_wifi_layrz_wifi_events_on_scan_result_response_get_error_details(LayrzWifiLayrzWifiEventsOnScanResultResponse* self) {
  g_return_val_if_fail(LAYRZ_WIFI_IS_LAYRZ_WIFI_EVENTS_ON_SCAN_RESULT_RESPONSE(self), nullptr);
  g_assert(layrz_wifi_layrz_wifi_events_on_scan_result_response_is_error(self));
  return fl_value_get_list_value(self->error, 2);
}

static void layrz_wifi_layrz_wifi_events_on_scan_result_cb(GObject* object, GAsyncResult* result, gpointer user_data) {
  GTask* task = G_TASK(user_data);
  g_task_return_pointer(task, result, g_object_unref);
}

void layrz_wifi_layrz_wifi_events_on_scan_result(LayrzWifiLayrzWifiEvents* self, LayrzWifiWifiNetwork* network, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data) {
  g_autoptr(FlValue) args = fl_value_new_list();
  fl_value_append_take(args, fl_value_new_custom_object(131, G_OBJECT(network)));
  g_autofree gchar* channel_name = g_strdup_printf("dev.flutter.pigeon.layrz_wifi.LayrzWifiEvents.onScanResult%s", self->suffix);
  g_autoptr(LayrzWifiMessageCodec) codec = layrz_wifi_message_codec_new();
  FlBasicMessageChannel* channel = fl_basic_message_channel_new(self->messenger, channel_name, FL_MESSAGE_CODEC(codec));
  GTask* task = g_task_new(self, cancellable, callback, user_data);
  g_task_set_task_data(task, channel, g_object_unref);
  fl_basic_message_channel_send(channel, args, cancellable, layrz_wifi_layrz_wifi_events_on_scan_result_cb, task);
}

LayrzWifiLayrzWifiEventsOnScanResultResponse* layrz_wifi_layrz_wifi_events_on_scan_result_finish(LayrzWifiLayrzWifiEvents* self, GAsyncResult* result, GError** error) {
  g_autoptr(GTask) task = G_TASK(result);
  GAsyncResult* r = G_ASYNC_RESULT(g_task_propagate_pointer(task, nullptr));
  FlBasicMessageChannel* channel = FL_BASIC_MESSAGE_CHANNEL(g_task_get_task_data(task));
  g_autoptr(FlValue) response = fl_basic_message_channel_send_finish(channel, r, error);
  if (response == nullptr) { 
    return nullptr;
  }
  return layrz_wifi_layrz_wifi_events_on_scan_result_response_new(response);
}

struct _LayrzWifiLayrzWifiEventsOnScanCompleteResponse {
  GObject parent_instance;

  FlValue* error;
};

G_DEFINE_TYPE(LayrzWifiLayrzWifiEventsOnScanCompleteResponse, layrz_wifi_layrz_wifi_events_on_scan_complete_response, G_TYPE_OBJECT)

static void layrz_wifi_layrz_wifi_events_on_scan_complete_response_dispose(GObject* object) {
  LayrzWifiLayrzWifiEventsOnScanCompleteResponse* self = LAYRZ_WIFI_LAYRZ_WIFI_EVENTS_ON_SCAN_COMPLETE_RESPONSE(object);
  g_clear_pointer(&self->error, fl_value_unref);
  G_OBJECT_CLASS(layrz_wifi_layrz_wifi_events_on_scan_complete_response_parent_class)->dispose(object);
}

static void layrz_wifi_layrz_wifi_events_on_scan_complete_response_init(LayrzWifiLayrzWifiEventsOnScanCompleteResponse* self) {
}

static void layrz_wifi_layrz_wifi_events_on_scan_complete_response_class_init(LayrzWifiLayrzWifiEventsOnScanCompleteResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = layrz_wifi_layrz_wifi_events_on_scan_complete_response_dispose;
}

static LayrzWifiLayrzWifiEventsOnScanCompleteResponse* layrz_wifi_layrz_wifi_events_on_scan_complete_response_new(FlValue* response) {
  LayrzWifiLayrzWifiEventsOnScanCompleteResponse* self = LAYRZ_WIFI_LAYRZ_WIFI_EVENTS_ON_SCAN_COMPLETE_RESPONSE(g_object_new(layrz_wifi_layrz_wifi_events_on_scan_complete_response_get_type(), nullptr));
  if (fl_value_get_length(response) > 1) {
    self->error = fl_value_ref(response);
  }
  return self;
}

gboolean layrz_wifi_layrz_wifi_events_on_scan_complete_response_is_error(LayrzWifiLayrzWifiEventsOnScanCompleteResponse* self) {
  g_return_val_if_fail(LAYRZ_WIFI_IS_LAYRZ_WIFI_EVENTS_ON_SCAN_COMPLETE_RESPONSE(self), FALSE);
  return self->error != nullptr;
}

const gchar* layrz_wifi_layrz_wifi_events_on_scan_complete_response_get_error_code(LayrzWifiLayrzWifiEventsOnScanCompleteResponse* self) {
  g_return_val_if_fail(LAYRZ_WIFI_IS_LAYRZ_WIFI_EVENTS_ON_SCAN_COMPLETE_RESPONSE(self), nullptr);
  g_assert(layrz_wifi_layrz_wifi_events_on_scan_complete_response_is_error(self));
  return fl_value_get_string(fl_value_get_list_value(self->error, 0));
}

const gchar* layrz_wifi_layrz_wifi_events_on_scan_complete_response_get_error_message(LayrzWifiLayrzWifiEventsOnScanCompleteResponse* self) {
  g_return_val_if_fail(LAYRZ_WIFI_IS_LAYRZ_WIFI_EVENTS_ON_SCAN_COMPLETE_RESPONSE(self), nullptr);
  g_assert(layrz_wifi_layrz_wifi_events_on_scan_complete_response_is_error(self));
  return fl_value_get_string(fl_value_get_list_value(self->error, 1));
}

FlValue* layrz_wifi_layrz_wifi_events_on_scan_complete_response_get_error_details(LayrzWifiLayrzWifiEventsOnScanCompleteResponse* self) {
  g_return_val_if_fail(LAYRZ_WIFI_IS_LAYRZ_WIFI_EVENTS_ON_SCAN_COMPLETE_RESPONSE(self), nullptr);
  g_assert(layrz_wifi_layrz_wifi_events_on_scan_complete_response_is_error(self));
  return fl_value_get_list_value(self->error, 2);
}

static void layrz_wifi_layrz_wifi_events_on_scan_complete_cb(GObject* object, GAsyncResult* result, gpointer user_data) {
  GTask* task = G_TASK(user_data);
  g_task_return_pointer(task, result, g_object_unref);
}

void layrz_wifi_layrz_wifi_events_on_scan_complete(LayrzWifiLayrzWifiEvents* self, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data) {
  g_autoptr(FlValue) args = fl_value_new_list();
  g_autofree gchar* channel_name = g_strdup_printf("dev.flutter.pigeon.layrz_wifi.LayrzWifiEvents.onScanComplete%s", self->suffix);
  g_autoptr(LayrzWifiMessageCodec) codec = layrz_wifi_message_codec_new();
  FlBasicMessageChannel* channel = fl_basic_message_channel_new(self->messenger, channel_name, FL_MESSAGE_CODEC(codec));
  GTask* task = g_task_new(self, cancellable, callback, user_data);
  g_task_set_task_data(task, channel, g_object_unref);
  fl_basic_message_channel_send(channel, args, cancellable, layrz_wifi_layrz_wifi_events_on_scan_complete_cb, task);
}

LayrzWifiLayrzWifiEventsOnScanCompleteResponse* layrz_wifi_layrz_wifi_events_on_scan_complete_finish(LayrzWifiLayrzWifiEvents* self, GAsyncResult* result, GError** error) {
  g_autoptr(GTask) task = G_TASK(result);
  GAsyncResult* r = G_ASYNC_RESULT(g_task_propagate_pointer(task, nullptr));
  FlBasicMessageChannel* channel = FL_BASIC_MESSAGE_CHANNEL(g_task_get_task_data(task));
  g_autoptr(FlValue) response = fl_basic_message_channel_send_finish(channel, r, error);
  if (response == nullptr) { 
    return nullptr;
  }
  return layrz_wifi_layrz_wifi_events_on_scan_complete_response_new(response);
}

struct _LayrzWifiLayrzWifiEventsOnScanErrorResponse {
  GObject parent_instance;

  FlValue* error;
};

G_DEFINE_TYPE(LayrzWifiLayrzWifiEventsOnScanErrorResponse, layrz_wifi_layrz_wifi_events_on_scan_error_response, G_TYPE_OBJECT)

static void layrz_wifi_layrz_wifi_events_on_scan_error_response_dispose(GObject* object) {
  LayrzWifiLayrzWifiEventsOnScanErrorResponse* self = LAYRZ_WIFI_LAYRZ_WIFI_EVENTS_ON_SCAN_ERROR_RESPONSE(object);
  g_clear_pointer(&self->error, fl_value_unref);
  G_OBJECT_CLASS(layrz_wifi_layrz_wifi_events_on_scan_error_response_parent_class)->dispose(object);
}

static void layrz_wifi_layrz_wifi_events_on_scan_error_response_init(LayrzWifiLayrzWifiEventsOnScanErrorResponse* self) {
}

static void layrz_wifi_layrz_wifi_events_on_scan_error_response_class_init(LayrzWifiLayrzWifiEventsOnScanErrorResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = layrz_wifi_layrz_wifi_events_on_scan_error_response_dispose;
}

static LayrzWifiLayrzWifiEventsOnScanErrorResponse* layrz_wifi_layrz_wifi_events_on_scan_error_response_new(FlValue* response) {
  LayrzWifiLayrzWifiEventsOnScanErrorResponse* self = LAYRZ_WIFI_LAYRZ_WIFI_EVENTS_ON_SCAN_ERROR_RESPONSE(g_object_new(layrz_wifi_layrz_wifi_events_on_scan_error_response_get_type(), nullptr));
  if (fl_value_get_length(response) > 1) {
    self->error = fl_value_ref(response);
  }
  return self;
}

gboolean layrz_wifi_layrz_wifi_events_on_scan_error_response_is_error(LayrzWifiLayrzWifiEventsOnScanErrorResponse* self) {
  g_return_val_if_fail(LAYRZ_WIFI_IS_LAYRZ_WIFI_EVENTS_ON_SCAN_ERROR_RESPONSE(self), FALSE);
  return self->error != nullptr;
}

const gchar* layrz_wifi_layrz_wifi_events_on_scan_error_response_get_error_code(LayrzWifiLayrzWifiEventsOnScanErrorResponse* self) {
  g_return_val_if_fail(LAYRZ_WIFI_IS_LAYRZ_WIFI_EVENTS_ON_SCAN_ERROR_RESPONSE(self), nullptr);
  g_assert(layrz_wifi_layrz_wifi_events_on_scan_error_response_is_error(self));
  return fl_value_get_string(fl_value_get_list_value(self->error, 0));
}

const gchar* layrz_wifi_layrz_wifi_events_on_scan_error_response_get_error_message(LayrzWifiLayrzWifiEventsOnScanErrorResponse* self) {
  g_return_val_if_fail(LAYRZ_WIFI_IS_LAYRZ_WIFI_EVENTS_ON_SCAN_ERROR_RESPONSE(self), nullptr);
  g_assert(layrz_wifi_layrz_wifi_events_on_scan_error_response_is_error(self));
  return fl_value_get_string(fl_value_get_list_value(self->error, 1));
}

FlValue* layrz_wifi_layrz_wifi_events_on_scan_error_response_get_error_details(LayrzWifiLayrzWifiEventsOnScanErrorResponse* self) {
  g_return_val_if_fail(LAYRZ_WIFI_IS_LAYRZ_WIFI_EVENTS_ON_SCAN_ERROR_RESPONSE(self), nullptr);
  g_assert(layrz_wifi_layrz_wifi_events_on_scan_error_response_is_error(self));
  return fl_value_get_list_value(self->error, 2);
}

static void layrz_wifi_layrz_wifi_events_on_scan_error_cb(GObject* object, GAsyncResult* result, gpointer user_data) {
  GTask* task = G_TASK(user_data);
  g_task_return_pointer(task, result, g_object_unref);
}

void layrz_wifi_layrz_wifi_events_on_scan_error(LayrzWifiLayrzWifiEvents* self, const gchar* message, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data) {
  g_autoptr(FlValue) args = fl_value_new_list();
  fl_value_append_take(args, fl_value_new_string(message));
  g_autofree gchar* channel_name = g_strdup_printf("dev.flutter.pigeon.layrz_wifi.LayrzWifiEvents.onScanError%s", self->suffix);
  g_autoptr(LayrzWifiMessageCodec) codec = layrz_wifi_message_codec_new();
  FlBasicMessageChannel* channel = fl_basic_message_channel_new(self->messenger, channel_name, FL_MESSAGE_CODEC(codec));
  GTask* task = g_task_new(self, cancellable, callback, user_data);
  g_task_set_task_data(task, channel, g_object_unref);
  fl_basic_message_channel_send(channel, args, cancellable, layrz_wifi_layrz_wifi_events_on_scan_error_cb, task);
}

LayrzWifiLayrzWifiEventsOnScanErrorResponse* layrz_wifi_layrz_wifi_events_on_scan_error_finish(LayrzWifiLayrzWifiEvents* self, GAsyncResult* result, GError** error) {
  g_autoptr(GTask) task = G_TASK(result);
  GAsyncResult* r = G_ASYNC_RESULT(g_task_propagate_pointer(task, nullptr));
  FlBasicMessageChannel* channel = FL_BASIC_MESSAGE_CHANNEL(g_task_get_task_data(task));
  g_autoptr(FlValue) response = fl_basic_message_channel_send_finish(channel, r, error);
  if (response == nullptr) { 
    return nullptr;
  }
  return layrz_wifi_layrz_wifi_events_on_scan_error_response_new(response);
}
