name: Run checks

on:
  pull_request:
    branches:
      - next
      - main
    types:
      - opened
      - synchronize
      - reopened

jobs:
  lint-dart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: goldenm-software/layrz-actions/.github/actions/check-dart@v1
        with:
          flutter-version: "3.41.9"
          run-tests: false

  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: goldenm-software/layrz-actions/.github/actions/changelog@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          post-comment: true
